# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\DOCU\Partial_Course_Admission_System\PartialCourseAdmission\UI\about.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_formAbout(object):
    def setupUi(self, formAbout):
        formAbout.setObjectName("formAbout")
        formAbout.resize(765, 679)
        self.label_2 = QtWidgets.QLabel(formAbout)
        self.label_2.setGeometry(QtCore.QRect(260, 10, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Bauhaus 93")
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.btnClose = QtWidgets.QPushButton(formAbout)
        self.btnClose.setGeometry(QtCore.QRect(320, 600, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnClose.setFont(font)
        self.btnClose.setObjectName("btnClose")
        self.gridLayoutWidget = QtWidgets.QWidget(formAbout)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 60, 681, 531))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.textBrowser = QtWidgets.QTextBrowser(self.gridLayoutWidget)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(formAbout)
        self.label.setGeometry(QtCore.QRect(220, 650, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(7)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(formAbout)
        self.line.setGeometry(QtCore.QRect(0, 640, 771, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.retranslateUi(formAbout)
        self.btnClose.clicked.connect(formAbout.close)
        QtCore.QMetaObject.connectSlotsByName(formAbout)

    def retranslateUi(self, formAbout):
        _translate = QtCore.QCoreApplication.translate
        formAbout.setWindowTitle(_translate("formAbout", "About"))
        self.label_2.setText(_translate("formAbout", "ABOUT & CREDITS"))
        self.btnClose.setText(_translate("formAbout", "CLOSE"))
        self.textBrowser.setHtml(_translate("formAbout", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#8b8b8b;\">  ___</span><span style=\" font-weight:600; color:#8b8b8b;\">________________________________________________________________________________________</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; color:#8b8b8b;\">________________________________________________  </span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#676767;\">   </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#676767;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7d7d7d;\">This system is based on the Cebu Technological University - Argao Campus partial admission on different courses for enrollment. </span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#1f3864;\">            The university offers different courses:</span><span style=\" font-family:\'Open Sans\'; font-size:8pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Symbol\'; font-size:8pt; color:#c00000;\">              </span><span style=\" font-family:\'Times New Roman\'; font-size:8pt; color:#c00000;\">👨🎓‍ </span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#c00000;\">Baccalaureate Degree </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Courier New\'; font-size:8pt; color:#7f7f7f;\">    o</span><span style=\" font-family:\'Times New Roman\'; font-size:8pt; color:#7f7f7f;\">   </span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">Bachelor of Science in Forestry (</span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; font-weight:600; color:#7f7f7f;\">BSF</span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">)</span><span style=\" font-family:\'Open Sans\'; font-size:8pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Courier New\'; font-size:8pt; color:#7f7f7f;\">    o</span><span style=\" font-family:\'Times New Roman\'; font-size:8pt; color:#7f7f7f;\">   </span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">Bachelor of Science in Agriculture (</span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; font-weight:600; color:#7f7f7f;\">BSA</span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">)</span><span style=\" font-family:\'Open Sans\'; font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Wingdings\'; font-size:8pt; color:#7f7f7f;\">      §</span><span style=\" font-family:\'Times New Roman\'; font-size:8pt; color:#7f7f7f;\">  </span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">Majors :</span><span style=\" font-family:\'Open Sans\'; font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Symbol\'; font-size:8pt; color:#7f7f7f;\">            ·</span><span style=\" font-family:\'Times New Roman\'; font-size:8pt; color:#7f7f7f;\">  </span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">Animal Science</span><span style=\" font-family:\'Open Sans\'; font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Symbol\'; font-size:8pt; color:#7f7f7f;\">            ·</span><span style=\" font-family:\'Times New Roman\'; font-size:8pt; color:#7f7f7f;\">  </span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">Horticulture</span><span style=\" font-family:\'Open Sans\'; font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Symbol\'; font-size:8pt; color:#7f7f7f;\">            ·</span><span style=\" font-family:\'Times New Roman\'; font-size:8pt; color:#7f7f7f;\">  </span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">Agronomy</span><span style=\" font-family:\'Open Sans\'; font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Symbol\'; font-size:8pt; color:#7f7f7f;\">            ·</span><span style=\" font-family:\'Times New Roman\'; font-size:8pt; color:#7f7f7f;\">  </span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">Crop Production</span><span style=\" font-family:\'Open Sans\'; font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Symbol\'; font-size:8pt; color:#7f7f7f;\">            ·</span><span style=\" font-family:\'Times New Roman\'; font-size:8pt; color:#7f7f7f;\">  </span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">Agricultural Economics</span><span style=\" font-family:\'Open Sans\'; font-size:8pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Courier New\'; font-size:8pt; color:#7f7f7f;\">    o</span><span style=\" font-family:\'Times New Roman\'; font-size:8pt; color:#7f7f7f;\">   </span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">Bachelor of Science in Industrial Engineering (</span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; font-weight:600; color:#7f7f7f;\">BSIE</span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">)</span><span style=\" font-family:\'Open Sans\'; font-size:8pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Courier New\'; font-size:8pt; color:#7f7f7f;\">    o</span><span style=\" font-family:\'Times New Roman\'; font-size:8pt; color:#7f7f7f;\">   </span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">Bachelor of Science in Information Technology (</span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; font-weight:600; color:#7f7f7f;\">BSIT</span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">)</span><span style=\" font-family:\'Open Sans\'; font-size:8pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Courier New\'; font-size:8pt; color:#7f7f7f;\">    o</span><span style=\" font-family:\'Times New Roman\'; font-size:8pt; color:#7f7f7f;\">   </span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">Bachelor of Science in Hospitality Management (</span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; font-weight:600; color:#7f7f7f;\">BSHM</span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">)</span><span style=\" font-family:\'Open Sans\'; font-size:8pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Courier New\'; font-size:8pt; color:#7f7f7f;\">    o</span><span style=\" font-family:\'Times New Roman\'; font-size:8pt; color:#7f7f7f;\">   </span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">Bachelor of Elementary Education (</span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; font-weight:600; color:#7f7f7f;\">BEED</span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">)</span><span style=\" font-family:\'Open Sans\'; font-size:8pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Courier New\'; font-size:8pt; color:#7f7f7f;\">    o</span><span style=\" font-family:\'Times New Roman\'; font-size:8pt; color:#7f7f7f;\">   </span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">Bachelor of Technology and Livelihood Education major in Home Economics (</span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; font-weight:600; color:#7f7f7f;\">BTLEd</span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">)</span><span style=\" font-family:\'Open Sans\'; font-size:8pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Courier New\'; font-size:8pt; color:#7f7f7f;\">    o</span><span style=\" font-family:\'Times New Roman\'; font-size:8pt; color:#7f7f7f;\">   </span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">Bachelor of Secondary Education major in Math (</span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; font-weight:600; color:#7f7f7f;\">BSED-Math</span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">)</span><span style=\" font-family:\'Open Sans\'; font-size:8pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Courier New\'; font-size:8pt; color:#7f7f7f;\">    o</span><span style=\" font-family:\'Times New Roman\'; font-size:8pt; color:#7f7f7f;\">   </span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">Bachelor of Arts in English Language Studies (</span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; font-weight:600; color:#7f7f7f;\">AB-ELs</span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">)</span><span style=\" font-family:\'Open Sans\'; font-size:8pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Courier New\'; font-size:8pt; color:#7f7f7f;\">    o</span><span style=\" font-family:\'Times New Roman\'; font-size:8pt; color:#7f7f7f;\">   </span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">Bachelor of Arts in Literature (</span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; font-weight:600; color:#7f7f7f;\">AB-Lit</span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">)</span><span style=\" font-family:\'Open Sans\'; font-size:8pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Courier New\'; font-size:8pt; color:#7f7f7f;\">    o</span><span style=\" font-family:\'Times New Roman\'; font-size:8pt; color:#7f7f7f;\">   </span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">Bachelor in Industrial Technology (</span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; font-weight:600; color:#7f7f7f;\">BIT</span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">)</span><span style=\" font-family:\'Open Sans\'; font-size:8pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Wingdings\'; font-size:8pt; color:#7f7f7f;\">      §</span><span style=\" font-family:\'Times New Roman\'; font-size:8pt; color:#7f7f7f;\">  </span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">Majors :</span><span style=\" font-family:\'Open Sans\'; font-size:8pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Symbol\'; font-size:8pt; color:#7f7f7f;\">            ·</span><span style=\" font-family:\'Times New Roman\'; font-size:8pt; color:#7f7f7f;\">  </span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">Garments Technology</span><span style=\" font-family:\'Open Sans\'; font-size:8pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Symbol\'; font-size:8pt; color:#7f7f7f;\">            ·</span><span style=\" font-family:\'Times New Roman\'; font-size:8pt; color:#7f7f7f;\">  </span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">Automotive Technology</span><span style=\" font-family:\'Open Sans\'; font-size:8pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Symbol\'; font-size:8pt; color:#7f7f7f;\">            ·</span><span style=\" font-family:\'Times New Roman\'; font-size:8pt; color:#7f7f7f;\">  </span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">Computer Technology</span><span style=\" font-family:\'Open Sans\'; font-size:8pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Symbol\'; font-size:8pt; color:#7f7f7f;\">            ·</span><span style=\" font-family:\'Times New Roman\'; font-size:8pt; color:#7f7f7f;\">  </span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">Drafting Technology</span><span style=\" font-family:\'Open Sans\'; font-size:8pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Symbol\'; font-size:8pt; color:#7f7f7f;\">            ·</span><span style=\" font-family:\'Times New Roman\'; font-size:8pt; color:#7f7f7f;\">  </span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">Electronics Technology</span><span style=\" font-family:\'Open Sans\'; font-size:8pt;\"> </span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%; font-family:\'Open Sans\'; font-size:8pt;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Times New Roman\'; font-size:8pt; color:#c00000;\">              👨‍⚖️ </span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#c00000;\">Graduate School courses</span><span style=\" font-family:\'Open Sans\'; font-size:8pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Courier New\'; font-size:8pt; color:#7f7f7f;\">    o</span><span style=\" font-family:\'Times New Roman\'; font-size:8pt; color:#7f7f7f;\">   </span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">Doctor in Development Education (</span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; font-weight:600; color:#7f7f7f;\">Dev.Ed.D.</span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">)</span><span style=\" font-family:\'Open Sans\'; font-size:8pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Courier New\'; font-size:8pt; color:#7f7f7f;\">    o</span><span style=\" font-family:\'Times New Roman\'; font-size:8pt; color:#7f7f7f;\">   </span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">Doctor in Philosophy major in Technology Management (</span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; font-weight:600; color:#7f7f7f;\">Ph.D. TM</span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">)</span><span style=\" font-family:\'Open Sans\'; font-size:8pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Courier New\'; font-size:8pt; color:#7f7f7f;\">    o</span><span style=\" font-family:\'Times New Roman\'; font-size:8pt; color:#7f7f7f;\">   </span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">Master of Arts in Education major in Administration and Supervision (</span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; font-weight:600; color:#7f7f7f;\">M.A.Ed. -AS</span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">)</span><span style=\" font-family:\'Open Sans\'; font-size:8pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Courier New\'; font-size:8pt; color:#7f7f7f;\">    o</span><span style=\" font-family:\'Times New Roman\'; font-size:8pt; color:#7f7f7f;\">   </span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">Master of Arts in Education major in Teaching Mathematics (</span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; font-weight:600; color:#7f7f7f;\">MAEd-TM</span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">)</span><span style=\" font-family:\'Open Sans\'; font-size:8pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Courier New\'; font-size:8pt; color:#7f7f7f;\">    o</span><span style=\" font-family:\'Times New Roman\'; font-size:8pt; color:#7f7f7f;\">   </span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">Master of Arts in Education major in English Language &amp; Literature Teaching (</span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; font-weight:600; color:#7f7f7f;\">MAed-ELLT</span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">)</span><span style=\" font-family:\'Open Sans\'; font-size:8pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Courier New\'; font-size:8pt; color:#7f7f7f;\">    o</span><span style=\" font-family:\'Times New Roman\'; font-size:8pt; color:#7f7f7f;\">   </span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">Master of Arts in Vocational Education (</span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; font-weight:600; color:#7f7f7f;\">MAVEd</span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">)</span><span style=\" font-family:\'Open Sans\'; font-size:8pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Courier New\'; font-size:8pt; color:#7f7f7f;\">    o</span><span style=\" font-family:\'Times New Roman\'; font-size:8pt; color:#7f7f7f;\">   </span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">Master in Public Administration (</span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; font-weight:600; color:#7f7f7f;\">MPA</span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">)</span><span style=\" font-family:\'Open Sans\'; font-size:8pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Courier New\'; font-size:8pt; color:#7f7f7f;\">    o</span><span style=\" font-family:\'Times New Roman\'; font-size:8pt; color:#7f7f7f;\">   </span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">Diploma / Certificate in Professional Education (</span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; font-weight:600; color:#7f7f7f;\">DPE/CPE</span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">)</span><span style=\" font-family:\'Open Sans\'; font-size:8pt;\"> </span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%; font-family:\'Open Sans\'; font-size:8pt;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"> <span style=\" color:#8b8b8b;\">  _________________________________________________________________________________________________________</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\">    </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\">    <span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">Partial Course Admission System (PCAS) </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%; font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%; font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">    Developed by:</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-size:8pt;\">    </span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">GRUPO #BSIT-2B</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%; font-size:8pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-size:8pt;\">    </span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">Leizel Mae Barrit</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-size:8pt;\">    </span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">James Kenneth Cañedo</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-size:8pt;\">    </span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">Ma. Consuelo Entoma</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-size:8pt;\">    </span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">Mary Angel Fuentes</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-size:8pt;\">    </span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">Jelly Ann Pananganan</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%; font-size:8pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-size:8pt;\">    </span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">Instructor:</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-size:8pt;\">    </span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">Dr. Melanie R. Albarracin</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%; font-size:8pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-size:8pt;\">    </span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">Information Technology Department </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">    Integrative Programming Technologies (IPT-PC 223)</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-size:8pt;\">    </span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">Cebu Technological University-Argao Campus</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-size:8pt;\">    </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-size:8pt;\">    </span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">This application/system was produced for educational use and non-profit purpose.</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%; font-size:8pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-size:8pt; font-weight:600; color:#717171;\">  ___________________________________________________________________________________________</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%; font-size:8pt; font-weight:600; color:#717171;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Segoe UI\'; font-size:7pt; font-style:italic; color:#7f7f7f;\">         </span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; font-style:italic; color:#7f7f7f;\">Image References:</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-size:8pt;\">    </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-size:8pt;\">    </span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">https://www.freelogodesign.org/</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-size:8pt;\">    </span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">https://www.wix.com/logo/maker</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-size:8pt;\">    </span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">https://www.pngitem.com/middle/hmbhbio_college-students-clipart-hd-png-download/</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-size:8pt;\">    </span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">https://www.ncsasports.org/naia-eligibility-center/transfer-rules</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-size:8pt;\">    </span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">https://www.canstockphoto.com/teens-campus-map-freshman-illustration-60227056.html</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">    https://www.123rf.com/photo_109970608_stock-vector-happy-group-of-teen-university-student-vector</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">    illustration-cartoon-character.html</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-size:8pt;\">    </span><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">https://clipartstation.com/wp-content/uploads/2017/11/college-students-clipart-3.jpg</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">    https://imgbin.com/download-png/CfHj6QM1</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Segoe UI\'; font-size:8pt; color:#7f7f7f;\">    https://www.pinclipart.com/downpngs/bimii_mouse-cursor-click-clipart-hand-cursor-hand-click/</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%; font-size:8pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-weight:600; color:#8b8b8b;\">________________________________________________  </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-size:8pt; font-weight:600; color:#717171;\">  ___________________________________________________________________________________________</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%; font-size:8pt;\"><br /></p></body></html>"))
        self.label.setText(_translate("formAbout", "© 2020 Partial Course Admission System (PCAS). All rights reserved."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    formAbout = QtWidgets.QWidget()
    ui = Ui_formAbout()
    ui.setupUi(formAbout)
    formAbout.show()
    sys.exit(app.exec_())
