# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\DOCU\Partial_Course_Admission_System\PartialCourseAdmission\UI\freshmen.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Freshmen(object):
    def setupUi(self, Freshmen):
        Freshmen.setObjectName("Freshmen")
        Freshmen.resize(900, 705)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        Freshmen.setFont(font)
        Freshmen.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.labelFreshmanTitle = QtWidgets.QLabel(Freshmen)
        self.labelFreshmanTitle.setGeometry(QtCore.QRect(250, -10, 401, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelFreshmanTitle.setFont(font)
        self.labelFreshmanTitle.setObjectName("labelFreshmanTitle")
        self.labelReq = QtWidgets.QLabel(Freshmen)
        self.labelReq.setGeometry(QtCore.QRect(100, 160, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelReq.setFont(font)
        self.labelReq.setObjectName("labelReq")
        self.labelFName = QtWidgets.QLabel(Freshmen)
        self.labelFName.setGeometry(QtCore.QRect(190, 60, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelFName.setFont(font)
        self.labelFName.setObjectName("labelFName")
        self.txtFName = QtWidgets.QLineEdit(Freshmen)
        self.txtFName.setGeometry(QtCore.QRect(280, 70, 150, 20))
        self.txtFName.setObjectName("txtFName")
        self.labelLName = QtWidgets.QLabel(Freshmen)
        self.labelLName.setGeometry(QtCore.QRect(450, 70, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelLName.setFont(font)
        self.labelLName.setObjectName("labelLName")
        self.txtLName = QtWidgets.QLineEdit(Freshmen)
        self.txtLName.setGeometry(QtCore.QRect(540, 70, 150, 20))
        self.txtLName.setObjectName("txtLName")
        self.labelMI = QtWidgets.QLabel(Freshmen)
        self.labelMI.setGeometry(QtCore.QRect(710, 70, 41, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelMI.setFont(font)
        self.labelMI.setObjectName("labelMI")
        self.txtMI = QtWidgets.QLineEdit(Freshmen)
        self.txtMI.setGeometry(QtCore.QRect(750, 70, 61, 20))
        self.txtMI.setObjectName("txtMI")
        self.labelCourse = QtWidgets.QLabel(Freshmen)
        self.labelCourse.setGeometry(QtCore.QRect(150, 130, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelCourse.setFont(font)
        self.labelCourse.setObjectName("labelCourse")
        self.cmbDCourse = QtWidgets.QComboBox(Freshmen)
        self.cmbDCourse.setGeometry(QtCore.QRect(280, 139, 301, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.cmbDCourse.setFont(font)
        self.cmbDCourse.setObjectName("cmbDCourse")
        self.cmbDCourse.addItem("")
        self.cmbDCourse.addItem("")
        self.cmbDCourse.addItem("")
        self.cmbDCourse.addItem("")
        self.cmbDCourse.addItem("")
        self.cmbDCourse.addItem("")
        self.cmbDCourse.addItem("")
        self.cmbDCourse.addItem("")
        self.cmbDCourse.addItem("")
        self.cmbDCourse.addItem("")
        self.cmbDCourse.addItem("")
        self.cmbDCourse.addItem("")
        self.cmbDCourse.addItem("")
        self.cmbDCourse.addItem("")
        self.cmbDCourse.addItem("")
        self.cmbDCourse.addItem("")
        self.cmbDCourse.addItem("")
        self.cmbDCourse.addItem("")
        self.cmbDCourse.addItem("")
        self.cmbDCourse.addItem("")
        self.checkBox = QtWidgets.QCheckBox(Freshmen)
        self.checkBox.setGeometry(QtCore.QRect(240, 190, 311, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(Freshmen)
        self.checkBox_2.setGeometry(QtCore.QRect(240, 210, 391, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(Freshmen)
        self.checkBox_3.setGeometry(QtCore.QRect(240, 230, 391, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.checkBox_3.setFont(font)
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(Freshmen)
        self.checkBox_4.setGeometry(QtCore.QRect(570, 230, 431, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.checkBox_4.setFont(font)
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(Freshmen)
        self.checkBox_5.setGeometry(QtCore.QRect(240, 250, 231, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.checkBox_5.setFont(font)
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(Freshmen)
        self.checkBox_6.setGeometry(QtCore.QRect(570, 250, 221, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.checkBox_6.setFont(font)
        self.checkBox_6.setObjectName("checkBox_6")
        self.btnClear = QtWidgets.QPushButton(Freshmen)
        self.btnClear.setGeometry(QtCore.QRect(520, 310, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnClear.setFont(font)
        self.btnClear.setObjectName("btnClear")
        self.btnSubmit = QtWidgets.QPushButton(Freshmen)
        self.btnSubmit.setGeometry(QtCore.QRect(350, 310, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnSubmit.setFont(font)
        self.btnSubmit.setObjectName("btnSubmit")
        self.labelAve = QtWidgets.QLabel(Freshmen)
        self.labelAve.setGeometry(QtCore.QRect(590, 140, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelAve.setFont(font)
        self.labelAve.setObjectName("labelAve")
        self.txtAve = QtWidgets.QLineEdit(Freshmen)
        self.txtAve.setGeometry(QtCore.QRect(730, 140, 81, 21))
        self.txtAve.setObjectName("txtAve")
        self.labelPrev = QtWidgets.QLabel(Freshmen)
        self.labelPrev.setGeometry(QtCore.QRect(70, 100, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelPrev.setFont(font)
        self.labelPrev.setObjectName("labelPrev")
        self.txtPrev = QtWidgets.QLineEdit(Freshmen)
        self.txtPrev.setGeometry(QtCore.QRect(280, 100, 531, 20))
        self.txtPrev.setObjectName("txtPrev")
        self.label_6 = QtWidgets.QLabel(Freshmen)
        self.label_6.setGeometry(QtCore.QRect(110, 260, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.labelTime = QtWidgets.QLabel(Freshmen)
        self.labelTime.setGeometry(QtCore.QRect(610, 280, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelTime.setFont(font)
        self.labelTime.setObjectName("labelTime")
        self.labelDate = QtWidgets.QLabel(Freshmen)
        self.labelDate.setGeometry(QtCore.QRect(380, 270, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelDate.setFont(font)
        self.labelDate.setObjectName("labelDate")
        self.Date = QtWidgets.QLineEdit(Freshmen)
        self.Date.setGeometry(QtCore.QRect(430, 280, 150, 20))
        self.Date.setObjectName("Date")
        self.Time = QtWidgets.QLineEdit(Freshmen)
        self.Time.setGeometry(QtCore.QRect(660, 280, 150, 20))
        self.Time.setObjectName("Time")
        self.btnDate = QtWidgets.QPushButton(Freshmen)
        self.btnDate.setGeometry(QtCore.QRect(100, 270, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnDate.setFont(font)
        self.btnDate.setObjectName("btnDate")
        self.btnSearch = QtWidgets.QPushButton(Freshmen)
        self.btnSearch.setGeometry(QtCore.QRect(720, 550, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btnSearch.setFont(font)
        self.btnSearch.setText("")
        self.btnSearch.setObjectName("btnSearch")
        self.txtSearch = QtWidgets.QLineEdit(Freshmen)
        self.txtSearch.setGeometry(QtCore.QRect(370, 550, 351, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.txtSearch.setFont(font)
        self.txtSearch.setObjectName("txtSearch")
        self.btnDelete = QtWidgets.QPushButton(Freshmen)
        self.btnDelete.setGeometry(QtCore.QRect(490, 600, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btnDelete.setFont(font)
        self.btnDelete.setObjectName("btnDelete")
        self.btnCancel = QtWidgets.QPushButton(Freshmen)
        self.btnCancel.setGeometry(QtCore.QRect(420, 660, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.btnCancel.setFont(font)
        self.btnCancel.setObjectName("btnCancel")
        self.line = QtWidgets.QFrame(Freshmen)
        self.line.setGeometry(QtCore.QRect(280, 640, 561, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Freshmen)
        self.line_2.setGeometry(QtCore.QRect(270, 520, 20, 131))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(Freshmen)
        self.line_3.setGeometry(QtCore.QRect(620, 510, 221, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(Freshmen)
        self.line_4.setGeometry(QtCore.QRect(830, 520, 20, 131))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(Freshmen)
        self.line_5.setGeometry(QtCore.QRect(280, 510, 31, 31))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.labelSUD = QtWidgets.QLabel(Freshmen)
        self.labelSUD.setGeometry(QtCore.QRect(310, 510, 311, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.labelSUD.setFont(font)
        self.labelSUD.setObjectName("labelSUD")
        self.line_6 = QtWidgets.QFrame(Freshmen)
        self.line_6.setGeometry(QtCore.QRect(40, 50, 20, 451))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(Freshmen)
        self.line_7.setGeometry(QtCore.QRect(830, 50, 20, 451))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(Freshmen)
        self.line_8.setGeometry(QtCore.QRect(50, 330, 791, 20))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(Freshmen)
        self.line_9.setGeometry(QtCore.QRect(290, 40, 551, 20))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_10 = QtWidgets.QFrame(Freshmen)
        self.line_10.setGeometry(QtCore.QRect(50, 40, 31, 21))
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.labelEnterInfo = QtWidgets.QLabel(Freshmen)
        self.labelEnterInfo.setGeometry(QtCore.QRect(80, 40, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.labelEnterInfo.setFont(font)
        self.labelEnterInfo.setObjectName("labelEnterInfo")
        self.line_11 = QtWidgets.QFrame(Freshmen)
        self.line_11.setGeometry(QtCore.QRect(50, 490, 791, 20))
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.btnAdd = QtWidgets.QPushButton(Freshmen)
        self.btnAdd.setGeometry(QtCore.QRect(430, 470, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btnAdd.setFont(font)
        self.btnAdd.setObjectName("btnAdd")
        self.tableFreshman = QtWidgets.QTableWidget(Freshmen)
        self.tableFreshman.setGeometry(QtCore.QRect(90, 360, 721, 111))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.tableFreshman.setFont(font)
        self.tableFreshman.setObjectName("tableFreshman")
        self.tableFreshman.setColumnCount(7)
        self.tableFreshman.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableFreshman.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFreshman.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFreshman.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFreshman.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFreshman.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFreshman.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFreshman.setHorizontalHeaderItem(6, item)
        self.labelViewAdd = QtWidgets.QLabel(Freshmen)
        self.labelViewAdd.setGeometry(QtCore.QRect(80, 340, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.labelViewAdd.setFont(font)
        self.labelViewAdd.setObjectName("labelViewAdd")
        self.checkBox_7 = QtWidgets.QCheckBox(Freshmen)
        self.checkBox_7.setGeometry(QtCore.QRect(570, 190, 171, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.checkBox_7.setFont(font)
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_8 = QtWidgets.QCheckBox(Freshmen)
        self.checkBox_8.setGeometry(QtCore.QRect(570, 210, 161, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.checkBox_8.setFont(font)
        self.checkBox_8.setObjectName("checkBox_8")
        self.btnClearSearch = QtWidgets.QPushButton(Freshmen)
        self.btnClearSearch.setGeometry(QtCore.QRect(650, 600, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btnClearSearch.setFont(font)
        self.btnClearSearch.setObjectName("btnClearSearch")
        self.btnUpdate = QtWidgets.QPushButton(Freshmen)
        self.btnUpdate.setGeometry(QtCore.QRect(330, 600, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btnUpdate.setFont(font)
        self.btnUpdate.setObjectName("btnUpdate")
        self.btnImage = QtWidgets.QPushButton(Freshmen)
        self.btnImage.setGeometry(QtCore.QRect(50, 500, 201, 151))
        self.btnImage.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.btnImage.setText("")
        self.btnImage.setFlat(True)
        self.btnImage.setObjectName("btnImage")

        self.retranslateUi(Freshmen)
        self.btnClearSearch.clicked.connect(self.txtSearch.clear)
        self.btnClearSearch.clicked.connect(self.txtFName.clear)
        self.btnClearSearch.clicked.connect(self.txtLName.clear)
        self.btnClearSearch.clicked.connect(self.txtMI.clear)
        self.btnClearSearch.clicked.connect(self.txtPrev.clear)
        self.btnClearSearch.clicked.connect(self.txtAve.clear)
        self.btnClearSearch.clicked['bool'].connect(self.checkBox.setChecked)
        self.btnClearSearch.clicked['bool'].connect(self.checkBox_2.setChecked)
        self.btnClearSearch.clicked['bool'].connect(self.checkBox_3.setChecked)
        self.btnClearSearch.clicked['bool'].connect(self.checkBox_5.setChecked)
        self.btnClearSearch.clicked['bool'].connect(self.checkBox_7.setChecked)
        self.btnClearSearch.clicked['bool'].connect(self.checkBox_8.setChecked)
        self.btnClearSearch.clicked['bool'].connect(self.checkBox_4.setChecked)
        self.btnClearSearch.clicked['bool'].connect(self.checkBox_6.setChecked)
        self.btnClearSearch.clicked.connect(self.Date.clear)
        self.btnClearSearch.clicked.connect(self.Time.clear)
        self.btnClear.clicked.connect(self.Time.clear)
        self.btnClear.clicked.connect(self.Date.clear)
        self.btnClear.clicked.connect(self.txtFName.clear)
        self.btnClear.clicked.connect(self.txtLName.clear)
        self.btnClear.clicked.connect(self.txtMI.clear)
        self.btnClear.clicked.connect(self.txtPrev.clear)
        self.btnClear.clicked.connect(self.txtAve.clear)
        self.btnClear.clicked['bool'].connect(self.checkBox.setChecked)
        self.btnClear.clicked['bool'].connect(self.checkBox_2.setChecked)
        self.btnClear.clicked['bool'].connect(self.checkBox_3.setChecked)
        self.btnClear.clicked['bool'].connect(self.checkBox_5.setChecked)
        self.btnClear.clicked['bool'].connect(self.checkBox_7.setChecked)
        self.btnClear.clicked['bool'].connect(self.checkBox_8.setChecked)
        self.btnClear.clicked['bool'].connect(self.checkBox_4.setChecked)
        self.btnClear.clicked['bool'].connect(self.checkBox_6.setChecked)
        self.btnCancel.clicked.connect(Freshmen.close)
        self.btnDelete.clicked.connect(self.tableFreshman.reset)
        QtCore.QMetaObject.connectSlotsByName(Freshmen)

    def retranslateUi(self, Freshmen):
        _translate = QtCore.QCoreApplication.translate
        Freshmen.setWindowTitle(_translate("Freshmen", "Freshman"))
        self.labelFreshmanTitle.setText(_translate("Freshmen", "Partial Admission for Freshman"))
        self.labelReq.setText(_translate("Freshmen", "General Requirements:"))
        self.labelFName.setText(_translate("Freshmen", "FirstName:"))
        self.labelLName.setText(_translate("Freshmen", "LastName:"))
        self.labelMI.setText(_translate("Freshmen", "M.I:"))
        self.labelCourse.setText(_translate("Freshmen", "Desired Course:"))
        self.cmbDCourse.setItemText(0, _translate("Freshmen", "Select Course"))
        self.cmbDCourse.setItemText(1, _translate("Freshmen", "Bachelor of Science in Hospitality Management (BSHM)"))
        self.cmbDCourse.setItemText(2, _translate("Freshmen", "Bachelor of Science in Information Technology (BSIT)"))
        self.cmbDCourse.setItemText(3, _translate("Freshmen", "Bachelor of Science in Industrial Engineering (BSIE)"))
        self.cmbDCourse.setItemText(4, _translate("Freshmen", "Bachelor in Industrial Technology major in Garments Technology (BIT-GT)"))
        self.cmbDCourse.setItemText(5, _translate("Freshmen", "Bachelor in Industrial Technology major in Automotive Technology (BIT-AT)"))
        self.cmbDCourse.setItemText(6, _translate("Freshmen", "Bachelor in Industrial Technology major in Computer Technology (BIT-CT)"))
        self.cmbDCourse.setItemText(7, _translate("Freshmen", "Bachelor in Industrial Technology major in Drafting Technology (BIT-DT)"))
        self.cmbDCourse.setItemText(8, _translate("Freshmen", "Bachelor in Industrial Technology major in Electronics Technology (BIT-ET)"))
        self.cmbDCourse.setItemText(9, _translate("Freshmen", "Bachelor of Arts in English Language Studies (AB-ELs)"))
        self.cmbDCourse.setItemText(10, _translate("Freshmen", "Bachelor of Arts in Literature (AB-Lit)"))
        self.cmbDCourse.setItemText(11, _translate("Freshmen", "Bachelor of Elementary Education (BEED)"))
        self.cmbDCourse.setItemText(12, _translate("Freshmen", "Bachelor of Secondary Education major in Math (BSED-Math)"))
        self.cmbDCourse.setItemText(13, _translate("Freshmen", "Bachelor of Technology and Livelihood Education major in Home Economics (BTLEd)"))
        self.cmbDCourse.setItemText(14, _translate("Freshmen", "Bachelor of Science in Agriculture major in Animal Science (BSA)"))
        self.cmbDCourse.setItemText(15, _translate("Freshmen", "Bachelor of Science in Agriculture major in Horticulture (BSA)"))
        self.cmbDCourse.setItemText(16, _translate("Freshmen", "Bachelor of Science in Agriculture major in Agronomy (BSA)"))
        self.cmbDCourse.setItemText(17, _translate("Freshmen", "Bachelor of Science in Agriculture major in Crop Production (BSA)"))
        self.cmbDCourse.setItemText(18, _translate("Freshmen", "Bachelor of Science in Agriculture major in Agricultural Economics (BSA)"))
        self.cmbDCourse.setItemText(19, _translate("Freshmen", "Bachelor of Science in Forestry (BSF)"))
        self.checkBox.setText(_translate("Freshmen", "Original Copy Of Form 138/SHS Report Card."))
        self.checkBox_2.setText(_translate("Freshmen", "Original Copy of NSO Authenticated Birth Certificate"))
        self.checkBox_3.setText(_translate("Freshmen", "Original Copy of Good Moral Character Certification"))
        self.checkBox_4.setText(_translate("Freshmen", "2 pcs. 2 X 2 ID Picture (for Registrar and SAO)"))
        self.checkBox_5.setText(_translate("Freshmen", "Original Copy of NCAE Result (if taker)"))
        self.checkBox_6.setText(_translate("Freshmen", "1 pc. 1 X 1 ID Picture (for Library Card)"))
        self.btnClear.setText(_translate("Freshmen", "Clear"))
        self.btnSubmit.setText(_translate("Freshmen", "Submit"))
        self.labelAve.setText(_translate("Freshmen", "General Average:"))
        self.labelPrev.setText(_translate("Freshmen", "Previous HighSchool/SHS:"))
        self.labelTime.setText(_translate("Freshmen", "Time:"))
        self.labelDate.setText(_translate("Freshmen", "Date:"))
        self.btnDate.setText(_translate("Freshmen", "Generate Date and Time"))
        self.txtSearch.setPlaceholderText(_translate("Freshmen", "Enter first name to search"))
        self.btnDelete.setText(_translate("Freshmen", "Delete"))
        self.btnCancel.setText(_translate("Freshmen", "Cancel"))
        self.labelSUD.setText(_translate("Freshmen", "Existing Record: Search-Update-Delete"))
        self.labelEnterInfo.setText(_translate("Freshmen", "Enter Information/Record"))
        self.btnAdd.setText(_translate("Freshmen", "Add"))
        item = self.tableFreshman.horizontalHeaderItem(0)
        item.setText(_translate("Freshmen", "FirstName"))
        item = self.tableFreshman.horizontalHeaderItem(1)
        item.setText(_translate("Freshmen", "MI"))
        item = self.tableFreshman.horizontalHeaderItem(2)
        item.setText(_translate("Freshmen", "LastName"))
        item = self.tableFreshman.horizontalHeaderItem(3)
        item.setText(_translate("Freshmen", "PreviousSchool"))
        item = self.tableFreshman.horizontalHeaderItem(4)
        item.setText(_translate("Freshmen", "GenAverage"))
        item = self.tableFreshman.horizontalHeaderItem(5)
        item.setText(_translate("Freshmen", "DesiredCourse"))
        item = self.tableFreshman.horizontalHeaderItem(6)
        item.setText(_translate("Freshmen", "Remarks"))
        self.labelViewAdd.setText(_translate("Freshmen", "View-Add Record"))
        self.checkBox_7.setText(_translate("Freshmen", "1 Long brown envelope"))
        self.checkBox_8.setText(_translate("Freshmen", "Medical Certificate"))
        self.btnClearSearch.setText(_translate("Freshmen", "Clear Search"))
        self.btnUpdate.setText(_translate("Freshmen", "Update"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Freshmen = QtWidgets.QWidget()
    ui = Ui_Freshmen()
    ui.setupUi(Freshmen)
    Freshmen.show()
    sys.exit(app.exec_())
