# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\DOCU\Partial_Course_Admission_System\PartialCourseAdmission\UI\gradSchool.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GraduateSchool(object):
    def setupUi(self, GraduateSchool):
        GraduateSchool.setObjectName("GraduateSchool")
        GraduateSchool.resize(902, 700)
        self.labelreq = QtWidgets.QLabel(GraduateSchool)
        self.labelreq.setGeometry(QtCore.QRect(260, 260, 311, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelreq.setFont(font)
        self.labelreq.setObjectName("labelreq")
        self.labelcourse = QtWidgets.QLabel(GraduateSchool)
        self.labelcourse.setGeometry(QtCore.QRect(260, 200, 291, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelcourse.setFont(font)
        self.labelcourse.setObjectName("labelcourse")
        self.cmbCourse = QtWidgets.QComboBox(GraduateSchool)
        self.cmbCourse.setGeometry(QtCore.QRect(360, 230, 501, 22))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.cmbCourse.setFont(font)
        self.cmbCourse.setEditable(False)
        self.cmbCourse.setObjectName("cmbCourse")
        self.cmbCourse.addItem("")
        self.cmbCourse.addItem("")
        self.cmbCourse.addItem("")
        self.cmbCourse.addItem("")
        self.cmbCourse.addItem("")
        self.cmbCourse.addItem("")
        self.cmbCourse.addItem("")
        self.cmbCourse.addItem("")
        self.cmbCourse.addItem("")
        self.checkBoxEnve = QtWidgets.QCheckBox(GraduateSchool)
        self.checkBoxEnve.setGeometry(QtCore.QRect(360, 370, 151, 17))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.checkBoxEnve.setFont(font)
        self.checkBoxEnve.setObjectName("checkBoxEnve")
        self.checkBoxTOR = QtWidgets.QCheckBox(GraduateSchool)
        self.checkBoxTOR.setGeometry(QtCore.QRect(360, 290, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.checkBoxTOR.setFont(font)
        self.checkBoxTOR.setObjectName("checkBoxTOR")
        self.checkBoxNSO = QtWidgets.QCheckBox(GraduateSchool)
        self.checkBoxNSO.setGeometry(QtCore.QRect(360, 310, 221, 17))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.checkBoxNSO.setFont(font)
        self.checkBoxNSO.setObjectName("checkBoxNSO")
        self.checkBoxGoodM = QtWidgets.QCheckBox(GraduateSchool)
        self.checkBoxGoodM.setGeometry(QtCore.QRect(360, 330, 351, 17))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.checkBoxGoodM.setFont(font)
        self.checkBoxGoodM.setObjectName("checkBoxGoodM")
        self.checkBox2x2 = QtWidgets.QCheckBox(GraduateSchool)
        self.checkBox2x2.setGeometry(QtCore.QRect(360, 350, 341, 17))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.checkBox2x2.setFont(font)
        self.checkBox2x2.setObjectName("checkBox2x2")
        self.txtSearch = QtWidgets.QLineEdit(GraduateSchool)
        self.txtSearch.setGeometry(QtCore.QRect(30, 389, 161, 31))
        self.txtSearch.setObjectName("txtSearch")
        self.btnDelete = QtWidgets.QPushButton(GraduateSchool)
        self.btnDelete.setGeometry(QtCore.QRect(80, 550, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnDelete.setFont(font)
        self.btnDelete.setObjectName("btnDelete")
        self.btnSearch = QtWidgets.QPushButton(GraduateSchool)
        self.btnSearch.setGeometry(QtCore.QRect(190, 390, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnSearch.setFont(font)
        self.btnSearch.setText("")
        self.btnSearch.setObjectName("btnSearch")
        self.labelpartialadgrads = QtWidgets.QLabel(GraduateSchool)
        self.labelpartialadgrads.setEnabled(True)
        self.labelpartialadgrads.setGeometry(QtCore.QRect(250, 10, 421, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Fax")
        font.setPointSize(16)
        font.setItalic(True)
        self.labelpartialadgrads.setFont(font)
        self.labelpartialadgrads.setObjectName("labelpartialadgrads")
        self.labellname = QtWidgets.QLabel(GraduateSchool)
        self.labellname.setGeometry(QtCore.QRect(270, 170, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labellname.setFont(font)
        self.labellname.setObjectName("labellname")
        self.txtLName = QtWidgets.QLineEdit(GraduateSchool)
        self.txtLName.setGeometry(QtCore.QRect(360, 170, 133, 20))
        self.txtLName.setObjectName("txtLName")
        self.txtFName = QtWidgets.QLineEdit(GraduateSchool)
        self.txtFName.setGeometry(QtCore.QRect(600, 170, 133, 20))
        self.txtFName.setObjectName("txtFName")
        self.labelfname = QtWidgets.QLabel(GraduateSchool)
        self.labelfname.setGeometry(QtCore.QRect(510, 170, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelfname.setFont(font)
        self.labelfname.setObjectName("labelfname")
        self.txtMI = QtWidgets.QLineEdit(GraduateSchool)
        self.txtMI.setGeometry(QtCore.QRect(800, 170, 61, 20))
        self.txtMI.setObjectName("txtMI")
        self.labelmi = QtWidgets.QLabel(GraduateSchool)
        self.labelmi.setGeometry(QtCore.QRect(760, 170, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelmi.setFont(font)
        self.labelmi.setObjectName("labelmi")
        self.btnClear = QtWidgets.QPushButton(GraduateSchool)
        self.btnClear.setGeometry(QtCore.QRect(600, 410, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnClear.setFont(font)
        self.btnClear.setObjectName("btnClear")
        self.labelid = QtWidgets.QLabel(GraduateSchool)
        self.labelid.setGeometry(QtCore.QRect(260, 130, 101, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelid.setFont(font)
        self.labelid.setObjectName("labelid")
        self.txtID = QtWidgets.QLineEdit(GraduateSchool)
        self.txtID.setGeometry(QtCore.QRect(360, 130, 131, 20))
        self.txtID.setObjectName("txtID")
        self.btnSubmit = QtWidgets.QPushButton(GraduateSchool)
        self.btnSubmit.setGeometry(QtCore.QRect(470, 410, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnSubmit.setFont(font)
        self.btnSubmit.setObjectName("btnSubmit")
        self.line_11 = QtWidgets.QFrame(GraduateSchool)
        self.line_11.setGeometry(QtCore.QRect(240, 620, 641, 20))
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.line_4 = QtWidgets.QFrame(GraduateSchool)
        self.line_4.setGeometry(QtCore.QRect(220, 300, 20, 331))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_8 = QtWidgets.QFrame(GraduateSchool)
        self.line_8.setGeometry(QtCore.QRect(240, 440, 641, 20))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_10 = QtWidgets.QFrame(GraduateSchool)
        self.line_10.setGeometry(QtCore.QRect(240, 80, 31, 21))
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.line_7 = QtWidgets.QFrame(GraduateSchool)
        self.line_7.setGeometry(QtCore.QRect(870, 90, 20, 541))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.labelsud = QtWidgets.QLabel(GraduateSchool)
        self.labelsud.setGeometry(QtCore.QRect(40, 330, 191, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.labelsud.setFont(font)
        self.labelsud.setObjectName("labelsud")
        self.line_9 = QtWidgets.QFrame(GraduateSchool)
        self.line_9.setGeometry(QtCore.QRect(480, 80, 401, 20))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.labeleir = QtWidgets.QLabel(GraduateSchool)
        self.labeleir.setGeometry(QtCore.QRect(270, 80, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.labeleir.setFont(font)
        self.labeleir.setObjectName("labeleir")
        self.line_2 = QtWidgets.QFrame(GraduateSchool)
        self.line_2.setGeometry(QtCore.QRect(10, 300, 20, 331))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(GraduateSchool)
        self.line_3.setGeometry(QtCore.QRect(20, 290, 211, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.labelvar = QtWidgets.QLabel(GraduateSchool)
        self.labelvar.setGeometry(QtCore.QRect(270, 450, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.labelvar.setFont(font)
        self.labelvar.setObjectName("labelvar")
        self.line_6 = QtWidgets.QFrame(GraduateSchool)
        self.line_6.setGeometry(QtCore.QRect(230, 90, 20, 541))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.labeler = QtWidgets.QLabel(GraduateSchool)
        self.labeler.setGeometry(QtCore.QRect(60, 310, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.labeler.setFont(font)
        self.labeler.setObjectName("labeler")
        self.line = QtWidgets.QFrame(GraduateSchool)
        self.line.setGeometry(QtCore.QRect(20, 620, 211, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.btnAdd = QtWidgets.QPushButton(GraduateSchool)
        self.btnAdd.setGeometry(QtCore.QRect(510, 590, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnAdd.setFont(font)
        self.btnAdd.setObjectName("btnAdd")
        self.tableGradSchool = QtWidgets.QTableWidget(GraduateSchool)
        self.tableGradSchool.setGeometry(QtCore.QRect(250, 470, 621, 111))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.tableGradSchool.setFont(font)
        self.tableGradSchool.setObjectName("tableGradSchool")
        self.tableGradSchool.setColumnCount(6)
        self.tableGradSchool.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableGradSchool.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableGradSchool.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableGradSchool.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableGradSchool.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableGradSchool.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableGradSchool.setHorizontalHeaderItem(5, item)
        self.btnClearSearch = QtWidgets.QPushButton(GraduateSchool)
        self.btnClearSearch.setGeometry(QtCore.QRect(80, 450, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnClearSearch.setFont(font)
        self.btnClearSearch.setObjectName("btnClearSearch")
        self.btnUpdate = QtWidgets.QPushButton(GraduateSchool)
        self.btnUpdate.setGeometry(QtCore.QRect(80, 500, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnUpdate.setFont(font)
        self.btnUpdate.setObjectName("btnUpdate")
        self.btnCancel = QtWidgets.QPushButton(GraduateSchool)
        self.btnCancel.setGeometry(QtCore.QRect(410, 650, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnCancel.setFont(font)
        self.btnCancel.setObjectName("btnCancel")
        self.btnImage = QtWidgets.QPushButton(GraduateSchool)
        self.btnImage.setGeometry(QtCore.QRect(20, 90, 211, 191))
        self.btnImage.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.btnImage.setText("")
        self.btnImage.setFlat(True)
        self.btnImage.setObjectName("btnImage")

        self.retranslateUi(GraduateSchool)
        self.btnCancel.clicked.connect(GraduateSchool.close)
        self.btnClear.clicked.connect(self.txtID.clear)
        self.btnClear.clicked.connect(self.txtLName.clear)
        self.btnClear.clicked.connect(self.txtFName.clear)
        self.btnClear.clicked.connect(self.txtMI.clear)
        self.btnClear.clicked.connect(self.cmbCourse.clearEditText)
        self.btnClear.clicked['bool'].connect(self.checkBoxTOR.setChecked)
        self.btnClear.clicked['bool'].connect(self.checkBoxNSO.setChecked)
        self.btnClear.clicked['bool'].connect(self.checkBoxGoodM.setChecked)
        self.btnClear.clicked['bool'].connect(self.checkBox2x2.setChecked)
        self.btnClear.clicked['bool'].connect(self.checkBoxEnve.setChecked)
        self.btnDelete.clicked.connect(self.tableGradSchool.reset)
        self.btnClearSearch.clicked.connect(self.txtSearch.clear)
        self.btnClearSearch.clicked.connect(self.txtID.clear)
        self.btnClearSearch.clicked.connect(self.txtLName.clear)
        self.btnClearSearch.clicked.connect(self.txtFName.clear)
        self.btnClearSearch.clicked.connect(self.txtMI.clear)
        self.btnClearSearch.clicked.connect(self.cmbCourse.clearEditText)
        self.btnClearSearch.clicked['bool'].connect(self.checkBoxTOR.setChecked)
        self.btnClearSearch.clicked['bool'].connect(self.checkBoxNSO.setChecked)
        self.btnClearSearch.clicked['bool'].connect(self.checkBoxGoodM.setChecked)
        self.btnClearSearch.clicked['bool'].connect(self.checkBox2x2.setChecked)
        self.btnClearSearch.clicked['bool'].connect(self.checkBoxEnve.setChecked)
        QtCore.QMetaObject.connectSlotsByName(GraduateSchool)

    def retranslateUi(self, GraduateSchool):
        _translate = QtCore.QCoreApplication.translate
        GraduateSchool.setWindowTitle(_translate("GraduateSchool", "Graduate School Applicant"))
        self.labelreq.setText(_translate("GraduateSchool", "Requirements for Grad School:"))
        self.labelcourse.setText(_translate("GraduateSchool", "Desired Graduate Studies\' Course:"))
        self.cmbCourse.setItemText(0, _translate("GraduateSchool", "Select Desired Course"))
        self.cmbCourse.setItemText(1, _translate("GraduateSchool", "Doctor in Development Education (Dev.Ed.D.)"))
        self.cmbCourse.setItemText(2, _translate("GraduateSchool", "Doctor in Philosophy major in Technology Management (Ph.D. TM)"))
        self.cmbCourse.setItemText(3, _translate("GraduateSchool", "Master of Arts in Education major in Administration and Supervision (M.A.Ed. -AS)"))
        self.cmbCourse.setItemText(4, _translate("GraduateSchool", "Master of Arts in Education major in Teaching Mathematics (MAEd-TM)"))
        self.cmbCourse.setItemText(5, _translate("GraduateSchool", "Master of Arts in Education major in English Language & Literature Teaching (MAed-ELLT)"))
        self.cmbCourse.setItemText(6, _translate("GraduateSchool", "Master of Arts in Vocational Education (MAVEd)"))
        self.cmbCourse.setItemText(7, _translate("GraduateSchool", "Master in Public Administration (MPA)"))
        self.cmbCourse.setItemText(8, _translate("GraduateSchool", "Diploma / Certificate in Professional Education (DPE/CPE)"))
        self.checkBoxEnve.setText(_translate("GraduateSchool", "1 long brown envelope"))
        self.checkBoxTOR.setText(_translate("GraduateSchool", "Transcript Records (TOR)"))
        self.checkBoxNSO.setText(_translate("GraduateSchool", "NSO Certificate (Original/Photocopy)"))
        self.checkBoxGoodM.setText(_translate("GraduateSchool", "Certificate of Good Moral Character (Original and Photocopy)"))
        self.checkBox2x2.setText(_translate("GraduateSchool", "2x2 Picture (2pcs.with white background and name tag)"))
        self.txtSearch.setPlaceholderText(_translate("GraduateSchool", "Enter ID Number to Search"))
        self.btnDelete.setText(_translate("GraduateSchool", "Delete"))
        self.labelpartialadgrads.setText(_translate("GraduateSchool", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Partial Admission for Graduate School</span></p></body></html>"))
        self.labellname.setText(_translate("GraduateSchool", "LastName:"))
        self.labelfname.setText(_translate("GraduateSchool", "FirstName:"))
        self.labelmi.setText(_translate("GraduateSchool", "M.I:"))
        self.btnClear.setText(_translate("GraduateSchool", "Clear"))
        self.labelid.setText(_translate("GraduateSchool", "ID Number:"))
        self.btnSubmit.setText(_translate("GraduateSchool", "Submit"))
        self.labelsud.setText(_translate("GraduateSchool", "Search-Update-Delete"))
        self.labeleir.setText(_translate("GraduateSchool", "Enter Information/Record"))
        self.labelvar.setText(_translate("GraduateSchool", "View-Add Record"))
        self.labeler.setText(_translate("GraduateSchool", "Existing Record:"))
        self.btnAdd.setText(_translate("GraduateSchool", "Add"))
        item = self.tableGradSchool.horizontalHeaderItem(0)
        item.setText(_translate("GraduateSchool", "IDNumber"))
        item = self.tableGradSchool.horizontalHeaderItem(1)
        item.setText(_translate("GraduateSchool", "LastName"))
        item = self.tableGradSchool.horizontalHeaderItem(2)
        item.setText(_translate("GraduateSchool", "FirstName"))
        item = self.tableGradSchool.horizontalHeaderItem(3)
        item.setText(_translate("GraduateSchool", "MI"))
        item = self.tableGradSchool.horizontalHeaderItem(4)
        item.setText(_translate("GraduateSchool", "DesiredCourse"))
        item = self.tableGradSchool.horizontalHeaderItem(5)
        item.setText(_translate("GraduateSchool", "Remarks"))
        self.btnClearSearch.setText(_translate("GraduateSchool", "Clear Search"))
        self.btnUpdate.setText(_translate("GraduateSchool", "Update"))
        self.btnCancel.setText(_translate("GraduateSchool", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GraduateSchool = QtWidgets.QWidget()
    ui = Ui_GraduateSchool()
    ui.setupUi(GraduateSchool)
    GraduateSchool.show()
    sys.exit(app.exec_())
