# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\DOCU\Partial_Course_Admission_System\PartialCourseAdmission\UI\MainUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(873, 723)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnOldStudent = QtWidgets.QPushButton(self.centralwidget)
        self.btnOldStudent.setGeometry(QtCore.QRect(530, 320, 181, 101))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.btnOldStudent.setFont(font)
        self.btnOldStudent.setObjectName("btnOldStudent")
        self.labelwelcome = QtWidgets.QLabel(self.centralwidget)
        self.labelwelcome.setGeometry(QtCore.QRect(290, 0, 311, 91))
        font = QtGui.QFont()
        font.setFamily("Bauhaus 93")
        font.setPointSize(50)
        self.labelwelcome.setFont(font)
        self.labelwelcome.setObjectName("labelwelcome")
        self.labelchoose = QtWidgets.QLabel(self.centralwidget)
        self.labelchoose.setGeometry(QtCore.QRect(260, 240, 361, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelchoose.setFont(font)
        self.labelchoose.setObjectName("labelchoose")
        self.labelpca = QtWidgets.QLabel(self.centralwidget)
        self.labelpca.setGeometry(QtCore.QRect(200, 90, 481, 41))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.labelpca.setFont(font)
        self.labelpca.setObjectName("labelpca")
        self.btnUserGuide = QtWidgets.QPushButton(self.centralwidget)
        self.btnUserGuide.setGeometry(QtCore.QRect(370, 540, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Open Sans Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnUserGuide.setFont(font)
        self.btnUserGuide.setObjectName("btnUserGuide")
        self.btnIncomingFreshman = QtWidgets.QPushButton(self.centralwidget)
        self.btnIncomingFreshman.setGeometry(QtCore.QRect(150, 320, 181, 101))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.btnIncomingFreshman.setFont(font)
        self.btnIncomingFreshman.setAutoFillBackground(False)
        self.btnIncomingFreshman.setObjectName("btnIncomingFreshman")
        self.btnSecDegree = QtWidgets.QPushButton(self.centralwidget)
        self.btnSecDegree.setGeometry(QtCore.QRect(150, 420, 281, 101))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.btnSecDegree.setFont(font)
        self.btnSecDegree.setObjectName("btnSecDegree")
        self.btnGradSchool = QtWidgets.QPushButton(self.centralwidget)
        self.btnGradSchool.setGeometry(QtCore.QRect(430, 420, 281, 101))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.btnGradSchool.setFont(font)
        self.btnGradSchool.setObjectName("btnGradSchool")
        self.btnExit = QtWidgets.QPushButton(self.centralwidget)
        self.btnExit.setGeometry(QtCore.QRect(590, 540, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Open Sans Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnExit.setFont(font)
        self.btnExit.setObjectName("btnExit")
        self.btnTransferee = QtWidgets.QPushButton(self.centralwidget)
        self.btnTransferee.setGeometry(QtCore.QRect(330, 320, 201, 101))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.btnTransferee.setFont(font)
        self.btnTransferee.setObjectName("btnTransferee")
        self.labelask = QtWidgets.QLabel(self.centralwidget)
        self.labelask.setGeometry(QtCore.QRect(360, 280, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.labelask.setFont(font)
        self.labelask.setObjectName("labelask")
        self.btnAbout = QtWidgets.QPushButton(self.centralwidget)
        self.btnAbout.setGeometry(QtCore.QRect(150, 540, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Open Sans Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnAbout.setFont(font)
        self.btnAbout.setObjectName("btnAbout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(300, 650, 281, 31))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(7)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 640, 881, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.btnImage = QtWidgets.QPushButton(self.centralwidget)
        self.btnImage.setGeometry(QtCore.QRect(320, 130, 241, 111))
        self.btnImage.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.btnImage.setText("")
        self.btnImage.setFlat(True)
        self.btnImage.setObjectName("btnImage")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 873, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.btnExit.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Partial Course Admission"))
        self.btnOldStudent.setText(_translate("MainWindow", "Old Student"))
        self.labelwelcome.setText(_translate("MainWindow", "WELCOME"))
        self.labelchoose.setText(_translate("MainWindow", "Choose your admission program:"))
        self.labelpca.setText(_translate("MainWindow", "CTU-AC PARTIAL COURSE ADMISSION "))
        self.btnUserGuide.setText(_translate("MainWindow", "USER GUIDE"))
        self.btnIncomingFreshman.setText(_translate("MainWindow", "Incoming Freshman"))
        self.btnSecDegree.setText(_translate("MainWindow", "Second Degree/Courser Applicant"))
        self.btnGradSchool.setText(_translate("MainWindow", "Graduate School"))
        self.btnExit.setText(_translate("MainWindow", "EXIT"))
        self.btnTransferee.setText(_translate("MainWindow", "Transferee"))
        self.labelask.setText(_translate("MainWindow", "Are you a / an?"))
        self.btnAbout.setText(_translate("MainWindow", "ABOUT"))
        self.label.setText(_translate("MainWindow", "© 2020 Partial Course Admission System (PCAS). All rights reserved."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
