# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\DOCU\Partial_Course_Admission_System\PartialCourseAdmission\UI\oldStudents.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OldStudent(object):
    def setupUi(self, OldStudent):
        OldStudent.setObjectName("OldStudent")
        OldStudent.resize(871, 697)
        self.labelOldStudentTitle = QtWidgets.QLabel(OldStudent)
        self.labelOldStudentTitle.setEnabled(True)
        self.labelOldStudentTitle.setGeometry(QtCore.QRect(240, 10, 411, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Calligraphy")
        font.setPointSize(12)
        self.labelOldStudentTitle.setFont(font)
        self.labelOldStudentTitle.setObjectName("labelOldStudentTitle")
        self.labelLName = QtWidgets.QLabel(OldStudent)
        self.labelLName.setGeometry(QtCore.QRect(60, 270, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelLName.setFont(font)
        self.labelLName.setObjectName("labelLName")
        self.txtLName = QtWidgets.QLineEdit(OldStudent)
        self.txtLName.setGeometry(QtCore.QRect(160, 270, 161, 20))
        self.txtLName.setObjectName("txtLName")
        self.labelFName = QtWidgets.QLabel(OldStudent)
        self.labelFName.setGeometry(QtCore.QRect(350, 270, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelFName.setFont(font)
        self.labelFName.setObjectName("labelFName")
        self.txtFName = QtWidgets.QLineEdit(OldStudent)
        self.txtFName.setGeometry(QtCore.QRect(450, 270, 191, 20))
        self.txtFName.setObjectName("txtFName")
        self.labelMI = QtWidgets.QLabel(OldStudent)
        self.labelMI.setGeometry(QtCore.QRect(690, 270, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelMI.setFont(font)
        self.labelMI.setObjectName("labelMI")
        self.txtMI = QtWidgets.QLineEdit(OldStudent)
        self.txtMI.setGeometry(QtCore.QRect(730, 270, 101, 20))
        self.txtMI.setObjectName("txtMI")
        self.labelIDNum = QtWidgets.QLabel(OldStudent)
        self.labelIDNum.setGeometry(QtCore.QRect(60, 300, 101, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelIDNum.setFont(font)
        self.labelIDNum.setObjectName("labelIDNum")
        self.txtID = QtWidgets.QLineEdit(OldStudent)
        self.txtID.setGeometry(QtCore.QRect(160, 300, 161, 20))
        self.txtID.setObjectName("txtID")
        self.labelCourse = QtWidgets.QLabel(OldStudent)
        self.labelCourse.setGeometry(QtCore.QRect(380, 300, 71, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelCourse.setFont(font)
        self.labelCourse.setObjectName("labelCourse")
        self.cmbCourse = QtWidgets.QComboBox(OldStudent)
        self.cmbCourse.setGeometry(QtCore.QRect(450, 300, 381, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.cmbCourse.setFont(font)
        self.cmbCourse.setObjectName("cmbCourse")
        self.cmbCourse.addItem("")
        self.cmbCourse.addItem("")
        self.cmbCourse.addItem("")
        self.cmbCourse.addItem("")
        self.cmbCourse.addItem("")
        self.cmbCourse.addItem("")
        self.cmbCourse.addItem("")
        self.cmbCourse.addItem("")
        self.cmbCourse.addItem("")
        self.cmbCourse.addItem("")
        self.cmbCourse.addItem("")
        self.cmbCourse.addItem("")
        self.cmbCourse.addItem("")
        self.cmbCourse.addItem("")
        self.cmbCourse.addItem("")
        self.cmbCourse.addItem("")
        self.cmbCourse.addItem("")
        self.cmbCourse.addItem("")
        self.cmbCourse.addItem("")
        self.cmbCourse.addItem("")
        self.cmbProgram = QtWidgets.QComboBox(OldStudent)
        self.cmbProgram.setGeometry(QtCore.QRect(160, 330, 161, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.cmbProgram.setFont(font)
        self.cmbProgram.setObjectName("cmbProgram")
        self.cmbProgram.addItem("")
        self.cmbProgram.addItem("")
        self.cmbProgram.addItem("")
        self.labelProgram = QtWidgets.QLabel(OldStudent)
        self.labelProgram.setGeometry(QtCore.QRect(80, 330, 91, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelProgram.setFont(font)
        self.labelProgram.setObjectName("labelProgram")
        self.cmbYear = QtWidgets.QComboBox(OldStudent)
        self.cmbYear.setGeometry(QtCore.QRect(450, 330, 381, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.cmbYear.setFont(font)
        self.cmbYear.setObjectName("cmbYear")
        self.cmbYear.addItem("")
        self.cmbYear.addItem("")
        self.cmbYear.addItem("")
        self.cmbYear.addItem("")
        self.cmbYear.addItem("")
        self.cmbYear.addItem("")
        self.labelYear = QtWidgets.QLabel(OldStudent)
        self.labelYear.setGeometry(QtCore.QRect(400, 330, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelYear.setFont(font)
        self.labelYear.setObjectName("labelYear")
        self.checkBox = QtWidgets.QCheckBox(OldStudent)
        self.checkBox.setGeometry(QtCore.QRect(290, 380, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.labelReq = QtWidgets.QLabel(OldStudent)
        self.labelReq.setGeometry(QtCore.QRect(60, 360, 251, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelReq.setFont(font)
        self.labelReq.setObjectName("labelReq")
        self.btnSubmit = QtWidgets.QPushButton(OldStudent)
        self.btnSubmit.setGeometry(QtCore.QRect(310, 420, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnSubmit.setFont(font)
        self.btnSubmit.setObjectName("btnSubmit")
        self.btnClear = QtWidgets.QPushButton(OldStudent)
        self.btnClear.setGeometry(QtCore.QRect(450, 420, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnClear.setFont(font)
        self.btnClear.setObjectName("btnClear")
        self.txtSearch = QtWidgets.QLineEdit(OldStudent)
        self.txtSearch.setGeometry(QtCore.QRect(360, 110, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtSearch.setFont(font)
        self.txtSearch.setObjectName("txtSearch")
        self.btnSearch = QtWidgets.QPushButton(OldStudent)
        self.btnSearch.setGeometry(QtCore.QRect(740, 110, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnSearch.setFont(font)
        self.btnSearch.setText("")
        self.btnSearch.setObjectName("btnSearch")
        self.btnDelete = QtWidgets.QPushButton(OldStudent)
        self.btnDelete.setGeometry(QtCore.QRect(510, 160, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnDelete.setFont(font)
        self.btnDelete.setObjectName("btnDelete")
        self.btnUpdate = QtWidgets.QPushButton(OldStudent)
        self.btnUpdate.setGeometry(QtCore.QRect(380, 160, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnUpdate.setFont(font)
        self.btnUpdate.setObjectName("btnUpdate")
        self.line_6 = QtWidgets.QFrame(OldStudent)
        self.line_6.setGeometry(QtCore.QRect(10, 240, 20, 401))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_10 = QtWidgets.QFrame(OldStudent)
        self.line_10.setGeometry(QtCore.QRect(20, 230, 31, 21))
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.labelSUD = QtWidgets.QLabel(OldStudent)
        self.labelSUD.setGeometry(QtCore.QRect(320, 60, 311, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.labelSUD.setFont(font)
        self.labelSUD.setObjectName("labelSUD")
        self.line_4 = QtWidgets.QFrame(OldStudent)
        self.line_4.setGeometry(QtCore.QRect(840, 70, 20, 151))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(OldStudent)
        self.line_5.setGeometry(QtCore.QRect(290, 56, 31, 31))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_7 = QtWidgets.QFrame(OldStudent)
        self.line_7.setGeometry(QtCore.QRect(840, 240, 20, 401))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.labelViewAdd = QtWidgets.QLabel(OldStudent)
        self.labelViewAdd.setGeometry(QtCore.QRect(50, 450, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.labelViewAdd.setFont(font)
        self.labelViewAdd.setObjectName("labelViewAdd")
        self.line_11 = QtWidgets.QFrame(OldStudent)
        self.line_11.setGeometry(QtCore.QRect(20, 630, 831, 20))
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.line_9 = QtWidgets.QFrame(OldStudent)
        self.line_9.setGeometry(QtCore.QRect(260, 230, 591, 20))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.labelEnterInfo = QtWidgets.QLabel(OldStudent)
        self.labelEnterInfo.setGeometry(QtCore.QRect(50, 230, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.labelEnterInfo.setFont(font)
        self.labelEnterInfo.setObjectName("labelEnterInfo")
        self.line_8 = QtWidgets.QFrame(OldStudent)
        self.line_8.setGeometry(QtCore.QRect(180, 450, 671, 21))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line = QtWidgets.QFrame(OldStudent)
        self.line.setGeometry(QtCore.QRect(290, 206, 561, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_12 = QtWidgets.QFrame(OldStudent)
        self.line_12.setGeometry(QtCore.QRect(20, 450, 31, 21))
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.line_2 = QtWidgets.QFrame(OldStudent)
        self.line_2.setGeometry(QtCore.QRect(280, 70, 20, 151))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(OldStudent)
        self.line_3.setGeometry(QtCore.QRect(630, 60, 221, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.btnCancel = QtWidgets.QPushButton(OldStudent)
        self.btnCancel.setGeometry(QtCore.QRect(390, 650, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnCancel.setFont(font)
        self.btnCancel.setObjectName("btnCancel")
        self.btnAdd = QtWidgets.QPushButton(OldStudent)
        self.btnAdd.setGeometry(QtCore.QRect(390, 610, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnAdd.setFont(font)
        self.btnAdd.setObjectName("btnAdd")
        self.tableOldStudent = QtWidgets.QTableWidget(OldStudent)
        self.tableOldStudent.setGeometry(QtCore.QRect(30, 470, 811, 131))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.tableOldStudent.setFont(font)
        self.tableOldStudent.setObjectName("tableOldStudent")
        self.tableOldStudent.setColumnCount(8)
        self.tableOldStudent.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableOldStudent.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableOldStudent.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableOldStudent.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableOldStudent.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableOldStudent.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableOldStudent.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableOldStudent.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableOldStudent.setHorizontalHeaderItem(7, item)
        self.btnClearSearch = QtWidgets.QPushButton(OldStudent)
        self.btnClearSearch.setGeometry(QtCore.QRect(640, 160, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnClearSearch.setFont(font)
        self.btnClearSearch.setObjectName("btnClearSearch")
        self.btnImage = QtWidgets.QPushButton(OldStudent)
        self.btnImage.setGeometry(QtCore.QRect(20, 70, 241, 151))
        self.btnImage.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.btnImage.setText("")
        self.btnImage.setFlat(True)
        self.btnImage.setObjectName("btnImage")

        self.retranslateUi(OldStudent)
        self.btnClear.clicked.connect(self.txtLName.clear)
        self.btnClear.clicked.connect(self.txtFName.clear)
        self.btnClear.clicked.connect(self.txtMI.clear)
        self.btnClear.clicked['bool'].connect(self.checkBox.setChecked)
        self.btnClear.clicked.connect(self.txtID.clear)
        self.btnClear.clicked.connect(self.cmbCourse.clearEditText)
        self.btnClear.clicked.connect(self.cmbYear.clearEditText)
        self.btnClear.clicked.connect(self.cmbProgram.clearEditText)
        self.btnDelete.clicked.connect(self.tableOldStudent.clearSelection)
        self.btnCancel.clicked.connect(OldStudent.close)
        self.btnClearSearch.clicked.connect(self.txtSearch.clear)
        self.btnClearSearch.clicked.connect(self.txtLName.clear)
        self.btnClearSearch.clicked.connect(self.txtFName.clear)
        self.btnClearSearch.clicked.connect(self.txtMI.clear)
        self.btnClearSearch.clicked.connect(self.cmbCourse.clearEditText)
        self.btnClearSearch.clicked.connect(self.cmbYear.clearEditText)
        self.btnClearSearch.clicked.connect(self.cmbProgram.clearEditText)
        self.btnClearSearch.clicked['bool'].connect(self.checkBox.setChecked)
        self.btnClearSearch.clicked.connect(self.txtID.clear)
        QtCore.QMetaObject.connectSlotsByName(OldStudent)

    def retranslateUi(self, OldStudent):
        _translate = QtCore.QCoreApplication.translate
        OldStudent.setWindowTitle(_translate("OldStudent", "Old Student"))
        self.labelOldStudentTitle.setText(_translate("OldStudent", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Partial Admission for Old Student</span></p></body></html>"))
        self.labelLName.setText(_translate("OldStudent", "Last Name:"))
        self.labelFName.setText(_translate("OldStudent", "First Name:"))
        self.labelMI.setText(_translate("OldStudent", "M.I:"))
        self.labelIDNum.setText(_translate("OldStudent", "ID Number:"))
        self.labelCourse.setText(_translate("OldStudent", "Course:"))
        self.cmbCourse.setItemText(0, _translate("OldStudent", "Select Course"))
        self.cmbCourse.setItemText(1, _translate("OldStudent", "Bachelor of Science in Forestry (BSF)"))
        self.cmbCourse.setItemText(2, _translate("OldStudent", "Bachelor of Science in Agriculture major in Animal Science (BSA)"))
        self.cmbCourse.setItemText(3, _translate("OldStudent", "Bachelor of Science in Agriculture major in Horticulture (BSA)"))
        self.cmbCourse.setItemText(4, _translate("OldStudent", "Bachelor of Science in Agriculture major in Agronomy (BSA)"))
        self.cmbCourse.setItemText(5, _translate("OldStudent", "Bachelor of Science in Agriculture major in Crop Production (BSA)"))
        self.cmbCourse.setItemText(6, _translate("OldStudent", "Bachelor of Science in Agriculture major in Agricultural Economics (BSA)"))
        self.cmbCourse.setItemText(7, _translate("OldStudent", "Bachelor of Science in Industrial Engineering (BSIE)"))
        self.cmbCourse.setItemText(8, _translate("OldStudent", "Bachelor of Science in Information Technology (BSIT)"))
        self.cmbCourse.setItemText(9, _translate("OldStudent", "Bachelor of Science in Hospitality Management (BSHM)"))
        self.cmbCourse.setItemText(10, _translate("OldStudent", "Bachelor of Elementary Education (BEED)"))
        self.cmbCourse.setItemText(11, _translate("OldStudent", "Bachelor of Technology and Livelihood Education major in Home Economics (BTLEd)"))
        self.cmbCourse.setItemText(12, _translate("OldStudent", "Bachelor of Secondary Education major in Math (BSED-Math)"))
        self.cmbCourse.setItemText(13, _translate("OldStudent", "Bachelor of Arts in English Language Studies (AB-ELs)"))
        self.cmbCourse.setItemText(14, _translate("OldStudent", "Bachelor of Arts in Literature (AB-Lit)"))
        self.cmbCourse.setItemText(15, _translate("OldStudent", "Bachelor in Industrial Technology major in Garments Technology (BIT-GT)"))
        self.cmbCourse.setItemText(16, _translate("OldStudent", "Bachelor in Industrial Technology major in Automotive Technology (BIT-AT)"))
        self.cmbCourse.setItemText(17, _translate("OldStudent", "Bachelor in Industrial Technology major in Computer  Technology (BIT-CT)"))
        self.cmbCourse.setItemText(18, _translate("OldStudent", "Bachelor in Industrial Technology major in Drafting  Technology (BIT-DT)"))
        self.cmbCourse.setItemText(19, _translate("OldStudent", "Bachelor in Industrial Technology major in Electronics Technology (BIT-ET)"))
        self.cmbProgram.setItemText(0, _translate("OldStudent", "Day/Night"))
        self.cmbProgram.setItemText(1, _translate("OldStudent", "Day"))
        self.cmbProgram.setItemText(2, _translate("OldStudent", "Night"))
        self.labelProgram.setText(_translate("OldStudent", "Program:"))
        self.cmbYear.setItemText(0, _translate("OldStudent", "Select Year"))
        self.cmbYear.setItemText(1, _translate("OldStudent", "1st Year"))
        self.cmbYear.setItemText(2, _translate("OldStudent", "2nd Year"))
        self.cmbYear.setItemText(3, _translate("OldStudent", "3rd Year"))
        self.cmbYear.setItemText(4, _translate("OldStudent", "4th Year"))
        self.cmbYear.setItemText(5, _translate("OldStudent", "5th Year"))
        self.labelYear.setText(_translate("OldStudent", "Year:"))
        self.checkBox.setText(_translate("OldStudent", "Grade Slip of the Previous Semester"))
        self.labelReq.setText(_translate("OldStudent", "Requirement for old students:"))
        self.btnSubmit.setText(_translate("OldStudent", "Submit"))
        self.btnClear.setText(_translate("OldStudent", "Clear"))
        self.txtSearch.setPlaceholderText(_translate("OldStudent", "Enter ID Number to search"))
        self.btnDelete.setText(_translate("OldStudent", "Delete"))
        self.btnUpdate.setText(_translate("OldStudent", "Update"))
        self.labelSUD.setText(_translate("OldStudent", "Existing Record: Search-Update-Delete"))
        self.labelViewAdd.setText(_translate("OldStudent", "View-Add Record"))
        self.labelEnterInfo.setText(_translate("OldStudent", "Enter Information/Record"))
        self.btnCancel.setText(_translate("OldStudent", "Cancel"))
        self.btnAdd.setText(_translate("OldStudent", "Add"))
        item = self.tableOldStudent.horizontalHeaderItem(0)
        item.setText(_translate("OldStudent", "LastName"))
        item = self.tableOldStudent.horizontalHeaderItem(1)
        item.setText(_translate("OldStudent", "FirstName"))
        item = self.tableOldStudent.horizontalHeaderItem(2)
        item.setText(_translate("OldStudent", "MI"))
        item = self.tableOldStudent.horizontalHeaderItem(3)
        item.setText(_translate("OldStudent", "IDNumber"))
        item = self.tableOldStudent.horizontalHeaderItem(4)
        item.setText(_translate("OldStudent", "Course"))
        item = self.tableOldStudent.horizontalHeaderItem(5)
        item.setText(_translate("OldStudent", "Program"))
        item = self.tableOldStudent.horizontalHeaderItem(6)
        item.setText(_translate("OldStudent", "Year"))
        item = self.tableOldStudent.horizontalHeaderItem(7)
        item.setText(_translate("OldStudent", "Remarks"))
        self.btnClearSearch.setText(_translate("OldStudent", "Clear Search"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OldStudent = QtWidgets.QWidget()
    ui = Ui_OldStudent()
    ui.setupUi(OldStudent)
    OldStudent.show()
    sys.exit(app.exec_())
