# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\DOCU\Partial_Course_Admission_System\PartialCourseAdmission\UI\transferees.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TransfereeStudent(object):
    def setupUi(self, TransfereeStudent):
        TransfereeStudent.setObjectName("TransfereeStudent")
        TransfereeStudent.resize(872, 670)
        self.labelTransfereeTitle = QtWidgets.QLabel(TransfereeStudent)
        self.labelTransfereeTitle.setGeometry(QtCore.QRect(220, 10, 441, 51))
        font = QtGui.QFont()
        font.setFamily("Pristina")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.labelTransfereeTitle.setFont(font)
        self.labelTransfereeTitle.setObjectName("labelTransfereeTitle")
        self.labelFName = QtWidgets.QLabel(TransfereeStudent)
        self.labelFName.setGeometry(QtCore.QRect(60, 110, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelFName.setFont(font)
        self.labelFName.setObjectName("labelFName")
        self.txtFName = QtWidgets.QLineEdit(TransfereeStudent)
        self.txtFName.setGeometry(QtCore.QRect(160, 110, 133, 20))
        self.txtFName.setObjectName("txtFName")
        self.labelCourse = QtWidgets.QLabel(TransfereeStudent)
        self.labelCourse.setGeometry(QtCore.QRect(80, 170, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelCourse.setFont(font)
        self.labelCourse.setObjectName("labelCourse")
        self.labelReq = QtWidgets.QLabel(TransfereeStudent)
        self.labelReq.setGeometry(QtCore.QRect(20, 200, 311, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelReq.setFont(font)
        self.labelReq.setObjectName("labelReq")
        self.btnClear = QtWidgets.QPushButton(TransfereeStudent)
        self.btnClear.setGeometry(QtCore.QRect(360, 370, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnClear.setFont(font)
        self.btnClear.setObjectName("btnClear")
        self.btnSubmit = QtWidgets.QPushButton(TransfereeStudent)
        self.btnSubmit.setGeometry(QtCore.QRect(240, 370, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnSubmit.setFont(font)
        self.btnSubmit.setObjectName("btnSubmit")
        self.checkBoxTOR = QtWidgets.QCheckBox(TransfereeStudent)
        self.checkBoxTOR.setGeometry(QtCore.QRect(160, 270, 70, 17))
        self.checkBoxTOR.setObjectName("checkBoxTOR")
        self.checkBox2x2 = QtWidgets.QCheckBox(TransfereeStudent)
        self.checkBox2x2.setGeometry(QtCore.QRect(160, 290, 351, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.checkBox2x2.setFont(font)
        self.checkBox2x2.setObjectName("checkBox2x2")
        self.checkBoxGoodM = QtWidgets.QCheckBox(TransfereeStudent)
        self.checkBoxGoodM.setGeometry(QtCore.QRect(160, 310, 301, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.checkBoxGoodM.setFont(font)
        self.checkBoxGoodM.setObjectName("checkBoxGoodM")
        self.checkBoxNSO = QtWidgets.QCheckBox(TransfereeStudent)
        self.checkBoxNSO.setGeometry(QtCore.QRect(160, 250, 321, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.checkBoxNSO.setFont(font)
        self.checkBoxNSO.setObjectName("checkBoxNSO")
        self.checkBox1x1 = QtWidgets.QCheckBox(TransfereeStudent)
        self.checkBox1x1.setGeometry(QtCore.QRect(160, 230, 241, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.checkBox1x1.setFont(font)
        self.checkBox1x1.setObjectName("checkBox1x1")
        self.cmbCourse = QtWidgets.QComboBox(TransfereeStudent)
        self.cmbCourse.setGeometry(QtCore.QRect(160, 170, 461, 22))
        self.cmbCourse.setObjectName("cmbCourse")
        self.cmbCourse.addItem("")
        self.cmbCourse.addItem("")
        self.cmbCourse.addItem("")
        self.cmbCourse.addItem("")
        self.cmbCourse.addItem("")
        self.cmbCourse.addItem("")
        self.cmbCourse.addItem("")
        self.cmbCourse.addItem("")
        self.cmbCourse.addItem("")
        self.cmbCourse.addItem("")
        self.cmbCourse.addItem("")
        self.cmbCourse.addItem("")
        self.cmbCourse.addItem("")
        self.cmbCourse.addItem("")
        self.cmbCourse.addItem("")
        self.cmbCourse.addItem("")
        self.cmbCourse.addItem("")
        self.cmbCourse.addItem("")
        self.cmbCourse.addItem("")
        self.cmbCourse.addItem("")
        self.labelLName = QtWidgets.QLabel(TransfereeStudent)
        self.labelLName.setGeometry(QtCore.QRect(300, 110, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelLName.setFont(font)
        self.labelLName.setObjectName("labelLName")
        self.txtLName = QtWidgets.QLineEdit(TransfereeStudent)
        self.txtLName.setGeometry(QtCore.QRect(390, 110, 133, 20))
        self.txtLName.setObjectName("txtLName")
        self.labelMI = QtWidgets.QLabel(TransfereeStudent)
        self.labelMI.setGeometry(QtCore.QRect(540, 110, 31, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelMI.setFont(font)
        self.labelMI.setObjectName("labelMI")
        self.txtMI = QtWidgets.QLineEdit(TransfereeStudent)
        self.txtMI.setGeometry(QtCore.QRect(570, 110, 51, 20))
        self.txtMI.setObjectName("txtMI")
        self.txtPrevSchool = QtWidgets.QLineEdit(TransfereeStudent)
        self.txtPrevSchool.setGeometry(QtCore.QRect(160, 140, 461, 20))
        self.txtPrevSchool.setObjectName("txtPrevSchool")
        self.checkBoxNCAE = QtWidgets.QCheckBox(TransfereeStudent)
        self.checkBoxNCAE.setGeometry(QtCore.QRect(160, 330, 231, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.checkBoxNCAE.setFont(font)
        self.checkBoxNCAE.setObjectName("checkBoxNCAE")
        self.btnSearch = QtWidgets.QPushButton(TransfereeStudent)
        self.btnSearch.setGeometry(QtCore.QRect(820, 380, 31, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        font.setItalic(True)
        self.btnSearch.setFont(font)
        self.btnSearch.setText("")
        self.btnSearch.setObjectName("btnSearch")
        self.txtSearch = QtWidgets.QLineEdit(TransfereeStudent)
        self.txtSearch.setGeometry(QtCore.QRect(670, 379, 151, 31))
        self.txtSearch.setObjectName("txtSearch")
        self.btnDelete = QtWidgets.QPushButton(TransfereeStudent)
        self.btnDelete.setGeometry(QtCore.QRect(710, 530, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnDelete.setFont(font)
        self.btnDelete.setObjectName("btnDelete")
        self.line_9 = QtWidgets.QFrame(TransfereeStudent)
        self.line_9.setGeometry(QtCore.QRect(250, 70, 401, 20))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_3 = QtWidgets.QFrame(TransfereeStudent)
        self.line_3.setGeometry(QtCore.QRect(660, 300, 201, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_2 = QtWidgets.QFrame(TransfereeStudent)
        self.line_2.setGeometry(QtCore.QRect(650, 310, 20, 291))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_8 = QtWidgets.QFrame(TransfereeStudent)
        self.line_8.setGeometry(QtCore.QRect(10, 400, 641, 20))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_10 = QtWidgets.QFrame(TransfereeStudent)
        self.line_10.setGeometry(QtCore.QRect(10, 70, 31, 21))
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.line_11 = QtWidgets.QFrame(TransfereeStudent)
        self.line_11.setGeometry(QtCore.QRect(10, 590, 641, 20))
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.labelSUD = QtWidgets.QLabel(TransfereeStudent)
        self.labelSUD.setGeometry(QtCore.QRect(670, 330, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.labelSUD.setFont(font)
        self.labelSUD.setObjectName("labelSUD")
        self.line = QtWidgets.QFrame(TransfereeStudent)
        self.line.setGeometry(QtCore.QRect(660, 590, 201, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_6 = QtWidgets.QFrame(TransfereeStudent)
        self.line_6.setGeometry(QtCore.QRect(0, 80, 20, 521))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(TransfereeStudent)
        self.line_7.setGeometry(QtCore.QRect(640, 80, 20, 521))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.labelInfo = QtWidgets.QLabel(TransfereeStudent)
        self.labelInfo.setGeometry(QtCore.QRect(40, 70, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.labelInfo.setFont(font)
        self.labelInfo.setObjectName("labelInfo")
        self.labelViewAdd = QtWidgets.QLabel(TransfereeStudent)
        self.labelViewAdd.setGeometry(QtCore.QRect(30, 410, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.labelViewAdd.setFont(font)
        self.labelViewAdd.setObjectName("labelViewAdd")
        self.line_4 = QtWidgets.QFrame(TransfereeStudent)
        self.line_4.setGeometry(QtCore.QRect(850, 310, 20, 291))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.labelPrevSchool = QtWidgets.QLabel(TransfereeStudent)
        self.labelPrevSchool.setGeometry(QtCore.QRect(20, 140, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelPrevSchool.setFont(font)
        self.labelPrevSchool.setObjectName("labelPrevSchool")
        self.btnCancel = QtWidgets.QPushButton(TransfereeStudent)
        self.btnCancel.setGeometry(QtCore.QRect(390, 620, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnCancel.setFont(font)
        self.btnCancel.setObjectName("btnCancel")
        self.tableTransferee = QtWidgets.QTableWidget(TransfereeStudent)
        self.tableTransferee.setGeometry(QtCore.QRect(20, 430, 621, 121))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.tableTransferee.setFont(font)
        self.tableTransferee.setObjectName("tableTransferee")
        self.tableTransferee.setColumnCount(6)
        self.tableTransferee.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableTransferee.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableTransferee.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableTransferee.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableTransferee.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableTransferee.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableTransferee.setHorizontalHeaderItem(5, item)
        self.btnAdd = QtWidgets.QPushButton(TransfereeStudent)
        self.btnAdd.setGeometry(QtCore.QRect(290, 560, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnAdd.setFont(font)
        self.btnAdd.setObjectName("btnAdd")
        self.labelExistRecord = QtWidgets.QLabel(TransfereeStudent)
        self.labelExistRecord.setGeometry(QtCore.QRect(700, 310, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.labelExistRecord.setFont(font)
        self.labelExistRecord.setObjectName("labelExistRecord")
        self.btnClearSearch = QtWidgets.QPushButton(TransfereeStudent)
        self.btnClearSearch.setGeometry(QtCore.QRect(710, 430, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnClearSearch.setFont(font)
        self.btnClearSearch.setObjectName("btnClearSearch")
        self.btnUpdate = QtWidgets.QPushButton(TransfereeStudent)
        self.btnUpdate.setGeometry(QtCore.QRect(710, 480, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnUpdate.setFont(font)
        self.btnUpdate.setObjectName("btnUpdate")
        self.btnImage = QtWidgets.QPushButton(TransfereeStudent)
        self.btnImage.setGeometry(QtCore.QRect(660, 80, 201, 201))
        self.btnImage.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.btnImage.setText("")
        self.btnImage.setFlat(True)
        self.btnImage.setObjectName("btnImage")

        self.retranslateUi(TransfereeStudent)
        self.btnClear.clicked.connect(self.txtFName.clear)
        self.btnClear.clicked.connect(self.txtLName.clear)
        self.btnClear.clicked.connect(self.txtMI.clear)
        self.btnClear.clicked.connect(self.txtPrevSchool.clear)
        self.btnClear.clicked.connect(self.cmbCourse.clearEditText)
        self.btnClear.clicked['bool'].connect(self.checkBox1x1.setChecked)
        self.btnClear.clicked['bool'].connect(self.checkBoxNSO.setChecked)
        self.btnClear.clicked['bool'].connect(self.checkBoxTOR.setChecked)
        self.btnClear.clicked['bool'].connect(self.checkBox2x2.setChecked)
        self.btnClear.clicked['bool'].connect(self.checkBoxGoodM.setChecked)
        self.btnClear.clicked['bool'].connect(self.checkBoxNCAE.setChecked)
        self.btnCancel.clicked.connect(TransfereeStudent.close)
        self.btnDelete.clicked.connect(self.tableTransferee.clearSelection)
        self.btnClearSearch.clicked.connect(self.txtSearch.clear)
        self.btnClearSearch.clicked.connect(self.txtMI.clear)
        self.btnClearSearch.clicked.connect(self.txtLName.clear)
        self.btnClearSearch.clicked.connect(self.txtFName.clear)
        self.btnClearSearch.clicked.connect(self.txtPrevSchool.clear)
        self.btnClearSearch.clicked.connect(self.cmbCourse.clearEditText)
        self.btnClearSearch.clicked['bool'].connect(self.checkBox1x1.setChecked)
        self.btnClearSearch.clicked['bool'].connect(self.checkBoxNSO.setChecked)
        self.btnClearSearch.clicked['bool'].connect(self.checkBoxTOR.setChecked)
        self.btnClearSearch.clicked['bool'].connect(self.checkBox2x2.setChecked)
        self.btnClearSearch.clicked['bool'].connect(self.checkBox2x2.setChecked)
        self.btnClearSearch.clicked['bool'].connect(self.checkBoxGoodM.setChecked)
        self.btnClearSearch.clicked['bool'].connect(self.checkBoxNCAE.setChecked)
        QtCore.QMetaObject.connectSlotsByName(TransfereeStudent)

    def retranslateUi(self, TransfereeStudent):
        _translate = QtCore.QCoreApplication.translate
        TransfereeStudent.setWindowTitle(_translate("TransfereeStudent", "Transferee"))
        self.labelTransfereeTitle.setText(_translate("TransfereeStudent", "Partial Admission for Transferee Student"))
        self.labelFName.setText(_translate("TransfereeStudent", "FirstName:"))
        self.labelCourse.setText(_translate("TransfereeStudent", "Courses:"))
        self.labelReq.setText(_translate("TransfereeStudent", "Requirements for Transferee Students:"))
        self.btnClear.setText(_translate("TransfereeStudent", "Clear"))
        self.btnSubmit.setText(_translate("TransfereeStudent", "Submit"))
        self.checkBoxTOR.setText(_translate("TransfereeStudent", "TOR"))
        self.checkBox2x2.setText(_translate("TransfereeStudent", "2 pcs. 2 X 2 ID Picture (Registrar\'s and SAO\'s Requirement"))
        self.checkBoxGoodM.setText(_translate("TransfereeStudent", "Original Copy of Good Moral Character Certification"))
        self.checkBoxNSO.setText(_translate("TransfereeStudent", "Original Copy of NSO Authenticated Birth Certificate"))
        self.checkBox1x1.setText(_translate("TransfereeStudent", "1 pc. 1 X 1 ID Picture (for Library Card)"))
        self.cmbCourse.setItemText(0, _translate("TransfereeStudent", "Select Course"))
        self.cmbCourse.setItemText(1, _translate("TransfereeStudent", "Bachelor of Science in Forestry (BSF)"))
        self.cmbCourse.setItemText(2, _translate("TransfereeStudent", "Bachelor of Science in Agriculture major in Animal Science (BSA)"))
        self.cmbCourse.setItemText(3, _translate("TransfereeStudent", "Bachelor of Science in Agriculture major in Horticulture (BSA)"))
        self.cmbCourse.setItemText(4, _translate("TransfereeStudent", "Bachelor of Science in Agriculture major in Agronomy (BSA)"))
        self.cmbCourse.setItemText(5, _translate("TransfereeStudent", "Bachelor of Science in Agriculture major in Crop Production (BSA)"))
        self.cmbCourse.setItemText(6, _translate("TransfereeStudent", "Bachelor of Science in Agriculture major in Agricultural Economics (BSA)"))
        self.cmbCourse.setItemText(7, _translate("TransfereeStudent", "Bachelor of Science in Industrial Engineering (BSIE)"))
        self.cmbCourse.setItemText(8, _translate("TransfereeStudent", "Bachelor of Science in Information Technology (BSIT)"))
        self.cmbCourse.setItemText(9, _translate("TransfereeStudent", "Bachelor of Science in Hospitality Management (BSHM)"))
        self.cmbCourse.setItemText(10, _translate("TransfereeStudent", "Bachelor of Elementary Education (BEED)"))
        self.cmbCourse.setItemText(11, _translate("TransfereeStudent", "Bachelor of Technology and Livelihood Education major in Home Economics (BTLEd)"))
        self.cmbCourse.setItemText(12, _translate("TransfereeStudent", "Bachelor of Secondary Education major in Math (BSED-Math)"))
        self.cmbCourse.setItemText(13, _translate("TransfereeStudent", "Bachelor of Arts in English Language Studies (AB-ELs)"))
        self.cmbCourse.setItemText(14, _translate("TransfereeStudent", "Bachelor of Arts in Literature (AB-Lit)"))
        self.cmbCourse.setItemText(15, _translate("TransfereeStudent", "Bachelor in Industrial Technology major in Garments Technology (BIT-GT)"))
        self.cmbCourse.setItemText(16, _translate("TransfereeStudent", "Bachelor in Industrial Technology major in Automotive Technology (BIT-AT)"))
        self.cmbCourse.setItemText(17, _translate("TransfereeStudent", "Bachelor in Industrial Technology major in Computer  Technology (BIT-CT)"))
        self.cmbCourse.setItemText(18, _translate("TransfereeStudent", "Bachelor in Industrial Technology major in Drafting  Technology (BIT-DT)"))
        self.cmbCourse.setItemText(19, _translate("TransfereeStudent", "Bachelor in Industrial Technology major in Electronics Technology (BIT-ET)"))
        self.labelLName.setText(_translate("TransfereeStudent", "LastName:"))
        self.labelMI.setText(_translate("TransfereeStudent", "M.I:"))
        self.checkBoxNCAE.setText(_translate("TransfereeStudent", "Original Copy of NCAE Result (if taker)"))
        self.txtSearch.setPlaceholderText(_translate("TransfereeStudent", "Enter First Name to search"))
        self.btnDelete.setText(_translate("TransfereeStudent", "Delete"))
        self.labelSUD.setText(_translate("TransfereeStudent", "Search-Update-Delete"))
        self.labelInfo.setText(_translate("TransfereeStudent", "Enter Information/Record"))
        self.labelViewAdd.setText(_translate("TransfereeStudent", "View-Add Record"))
        self.labelPrevSchool.setText(_translate("TransfereeStudent", "Previous School:"))
        self.btnCancel.setText(_translate("TransfereeStudent", "Cancel"))
        item = self.tableTransferee.horizontalHeaderItem(0)
        item.setText(_translate("TransfereeStudent", "FirstName"))
        item = self.tableTransferee.horizontalHeaderItem(1)
        item.setText(_translate("TransfereeStudent", "MI"))
        item = self.tableTransferee.horizontalHeaderItem(2)
        item.setText(_translate("TransfereeStudent", "LastName"))
        item = self.tableTransferee.horizontalHeaderItem(3)
        item.setText(_translate("TransfereeStudent", "PreviousSchool"))
        item = self.tableTransferee.horizontalHeaderItem(4)
        item.setText(_translate("TransfereeStudent", "DesiredCourse"))
        item = self.tableTransferee.horizontalHeaderItem(5)
        item.setText(_translate("TransfereeStudent", "Remarks"))
        self.btnAdd.setText(_translate("TransfereeStudent", "Add"))
        self.labelExistRecord.setText(_translate("TransfereeStudent", "Existing Record"))
        self.btnClearSearch.setText(_translate("TransfereeStudent", "Clear Search"))
        self.btnUpdate.setText(_translate("TransfereeStudent", "Update"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TransfereeStudent = QtWidgets.QWidget()
    ui = Ui_TransfereeStudent()
    ui.setupUi(TransfereeStudent)
    TransfereeStudent.show()
    sys.exit(app.exec_())
