# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\DOCU\Partial_Course_Admission_System\PartialCourseAdmission\UI\userGuide.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
path = 'D:/DOCU/Partial_Course_Admission_System/PartialCourseAdmission' # <-- NOTE: Set & edit folder path here from your D: drive where this project folder is placed.

class Ui_formGuide(object):
    def setupUi(self, formGuide):
        formGuide.setObjectName("formGuide")
        formGuide.resize(761, 700)
        self.label_2 = QtWidgets.QLabel(formGuide)
        self.label_2.setGeometry(QtCore.QRect(310, 0, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Bauhaus 93")
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayoutWidget = QtWidgets.QWidget(formGuide)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 40, 761, 571))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.tabUserGuide = QtWidgets.QTabWidget(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(9)
        self.tabUserGuide.setFont(font)
        self.tabUserGuide.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabUserGuide.setMovable(False)
        self.tabUserGuide.setObjectName("tabUserGuide")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 20, 711, 501))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.gridLayoutWidget_2)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_2.addWidget(self.textBrowser, 0, 0, 1, 1)
        self.tabUserGuide.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.tab_3)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(60, 20, 621, 161))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.gridLayoutWidget_3)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.gridLayout_3.addWidget(self.textBrowser_2, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab_3)
        self.label_4.setGeometry(QtCore.QRect(160, 190, 431, 351))
        self.label_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("image/Capture_1.0_MainWindow.JPG"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.tabUserGuide.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(30, 10, 691, 81))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.gridLayoutWidget_4)
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.gridLayout_4.addWidget(self.textBrowser_3, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setGeometry(QtCore.QRect(130, 100, 471, 411))
        self.label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("image/Capture_2.0_SampleOldStudent.JPG"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.tabUserGuide.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.tab_4)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(20, 10, 721, 101))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.gridLayoutWidget_5)
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.gridLayout_5.addWidget(self.textBrowser_4, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab_4)
        self.label_5.setGeometry(QtCore.QRect(20, 130, 501, 411))
        self.label_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("image/Capture_3.0_CreateReadAddUserInfo.JPG"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_18 = QtWidgets.QLabel(self.tab_4)
        self.label_18.setGeometry(QtCore.QRect(160, 370, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.tab_4)
        self.label_19.setGeometry(QtCore.QRect(600, 260, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.tab_4)
        self.label_20.setGeometry(QtCore.QRect(170, 490, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.tab_4)
        self.label_21.setGeometry(QtCore.QRect(210, 470, 51, 71))
        self.label_21.setText("")
        self.label_21.setPixmap(QtGui.QPixmap("image/handclickRight.png"))
        self.label_21.setScaledContents(True)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.tab_4)
        self.label_22.setGeometry(QtCore.QRect(210, 400, 31, 41))
        self.label_22.setText("")
        self.label_22.setPixmap(QtGui.QPixmap("image/handclick.png"))
        self.label_22.setScaledContents(True)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.tab_4)
        self.label_23.setGeometry(QtCore.QRect(510, 430, 241, 71))
        self.label_23.setText("")
        self.label_23.setPixmap(QtGui.QPixmap("image/Capture_3.1_QMessagePromptIncomplete.jpg"))
        self.label_23.setScaledContents(True)
        self.label_23.setObjectName("label_23")
        self.label_50 = QtWidgets.QLabel(self.tab_4)
        self.label_50.setGeometry(QtCore.QRect(530, 510, 71, 31))
        self.label_50.setText("")
        self.label_50.setPixmap(QtGui.QPixmap("image/arrowRight.png"))
        self.label_50.setScaledContents(True)
        self.label_50.setObjectName("label_50")
        self.label_24 = QtWidgets.QLabel(self.tab_4)
        self.label_24.setGeometry(QtCore.QRect(700, 480, 31, 41))
        self.label_24.setText("")
        self.label_24.setPixmap(QtGui.QPixmap("image/handclick.png"))
        self.label_24.setScaledContents(True)
        self.label_24.setObjectName("label_24")
        self.label_51 = QtWidgets.QLabel(self.tab_4)
        self.label_51.setGeometry(QtCore.QRect(520, 370, 71, 31))
        self.label_51.setText("")
        self.label_51.setPixmap(QtGui.QPixmap("image/arrowRight.png"))
        self.label_51.setScaledContents(True)
        self.label_51.setObjectName("label_51")
        self.label_25 = QtWidgets.QLabel(self.tab_4)
        self.label_25.setGeometry(QtCore.QRect(510, 300, 171, 71))
        self.label_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_25.setText("")
        self.label_25.setPixmap(QtGui.QPixmap("image/Capture_QMessage_Submitted.JPG"))
        self.label_25.setScaledContents(True)
        self.label_25.setObjectName("label_25")
        self.label_52 = QtWidgets.QLabel(self.tab_4)
        self.label_52.setGeometry(QtCore.QRect(630, 350, 31, 41))
        self.label_52.setText("")
        self.label_52.setPixmap(QtGui.QPixmap("image/handclick.png"))
        self.label_52.setScaledContents(True)
        self.label_52.setObjectName("label_52")
        self.label_53 = QtWidgets.QLabel(self.tab_4)
        self.label_53.setGeometry(QtCore.QRect(610, 510, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_53.setFont(font)
        self.label_53.setObjectName("label_53")
        self.tabUserGuide.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.tab_5)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(20, 10, 711, 73))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.gridLayoutWidget_6)
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.gridLayout_6.addWidget(self.textBrowser_5, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab_5)
        self.label_6.setGeometry(QtCore.QRect(20, 90, 491, 431))
        self.label_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("image/Capture_4.0_QMessagePrompt.JPG"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab_5)
        self.label_7.setGeometry(QtCore.QRect(470, 150, 271, 91))
        self.label_7.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("image/Capture_4.1_QMessagePromptComplete.JPG"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab_5)
        self.label_8.setGeometry(QtCore.QRect(520, 380, 71, 81))
        self.label_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("image/Capture_4.2_QInfo.JPG"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab_5)
        self.label_9.setGeometry(QtCore.QRect(560, 250, 51, 121))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("image/arrowUp.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab_5)
        self.label_10.setGeometry(QtCore.QRect(420, 330, 51, 61))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("image/arrowUp.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab_5)
        self.label_11.setGeometry(QtCore.QRect(590, 260, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab_5)
        self.label_12.setGeometry(QtCore.QRect(420, 311, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_97 = QtWidgets.QLabel(self.tab_5)
        self.label_97.setGeometry(QtCore.QRect(700, 220, 31, 41))
        self.label_97.setText("")
        self.label_97.setPixmap(QtGui.QPixmap("image/handclick.png"))
        self.label_97.setScaledContents(True)
        self.label_97.setObjectName("label_97")
        self.label_98 = QtWidgets.QLabel(self.tab_5)
        self.label_98.setGeometry(QtCore.QRect(380, 330, 31, 41))
        self.label_98.setText("")
        self.label_98.setPixmap(QtGui.QPixmap("image/handclick.png"))
        self.label_98.setScaledContents(True)
        self.label_98.setObjectName("label_98")
        self.tabUserGuide.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayoutWidget_7 = QtWidgets.QWidget(self.tab_6)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(20, 10, 711, 151))
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.textBrowser_6 = QtWidgets.QTextBrowser(self.gridLayoutWidget_7)
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.gridLayout_7.addWidget(self.textBrowser_6, 0, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.tab_6)
        self.label_13.setGeometry(QtCore.QRect(300, 170, 431, 371))
        self.label_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("image/Capture_5.0_SearchtoUpdate.JPG"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tab_6)
        self.label_14.setGeometry(QtCore.QRect(10, 190, 241, 71))
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("image/Capture_5.1_QMessageUpdatedRecord.JPG"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.label_26 = QtWidgets.QLabel(self.tab_6)
        self.label_26.setGeometry(QtCore.QRect(450, 240, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.tab_6)
        self.label_27.setGeometry(QtCore.QRect(700, 240, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.tab_6)
        self.label_28.setGeometry(QtCore.QRect(180, 320, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.tab_6)
        self.label_29.setGeometry(QtCore.QRect(420, 391, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.tab_6)
        self.label_30.setGeometry(QtCore.QRect(260, 290, 47, 121))
        font = QtGui.QFont()
        font.setPointSize(72)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.tab_6)
        self.label_31.setGeometry(QtCore.QRect(200, 240, 31, 41))
        self.label_31.setText("")
        self.label_31.setTextFormat(QtCore.Qt.PlainText)
        self.label_31.setPixmap(QtGui.QPixmap("image/handclick.png"))
        self.label_31.setScaledContents(True)
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.tab_6)
        self.label_32.setGeometry(QtCore.QRect(110, 480, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.tab_6)
        self.label_33.setGeometry(QtCore.QRect(460, 410, 31, 41))
        self.label_33.setText("")
        self.label_33.setPixmap(QtGui.QPixmap("image/handclick.png"))
        self.label_33.setScaledContents(True)
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.tab_6)
        self.label_34.setGeometry(QtCore.QRect(670, 250, 31, 41))
        self.label_34.setText("")
        self.label_34.setTextFormat(QtCore.Qt.PlainText)
        self.label_34.setPixmap(QtGui.QPixmap("image/handclick.png"))
        self.label_34.setScaledContents(True)
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.tab_6)
        self.label_35.setGeometry(QtCore.QRect(130, 350, 131, 31))
        self.label_35.setObjectName("label_35")
        self.label_54 = QtWidgets.QLabel(self.tab_6)
        self.label_54.setGeometry(QtCore.QRect(490, 270, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_54.setFont(font)
        self.label_54.setObjectName("label_54")
        self.label_55 = QtWidgets.QLabel(self.tab_6)
        self.label_55.setGeometry(QtCore.QRect(110, 250, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_55.setFont(font)
        self.label_55.setObjectName("label_55")
        self.label_56 = QtWidgets.QLabel(self.tab_6)
        self.label_56.setGeometry(QtCore.QRect(220, 470, 71, 31))
        self.label_56.setText("")
        self.label_56.setPixmap(QtGui.QPixmap("image/arrowRight.png"))
        self.label_56.setScaledContents(True)
        self.label_56.setObjectName("label_56")
        self.label_57 = QtWidgets.QLabel(self.tab_6)
        self.label_57.setGeometry(QtCore.QRect(40, 410, 181, 71))
        self.label_57.setText("")
        self.label_57.setPixmap(QtGui.QPixmap("image/Capture_QMessage_Submitted.JPG"))
        self.label_57.setScaledContents(True)
        self.label_57.setObjectName("label_57")
        self.label_58 = QtWidgets.QLabel(self.tab_6)
        self.label_58.setGeometry(QtCore.QRect(190, 460, 31, 41))
        self.label_58.setText("")
        self.label_58.setTextFormat(QtCore.Qt.PlainText)
        self.label_58.setPixmap(QtGui.QPixmap("image/handclick.png"))
        self.label_58.setScaledContents(True)
        self.label_58.setObjectName("label_58")
        self.label_59 = QtWidgets.QLabel(self.tab_6)
        self.label_59.setGeometry(QtCore.QRect(520, 270, 31, 41))
        self.label_59.setText("")
        self.label_59.setTextFormat(QtCore.Qt.PlainText)
        self.label_59.setPixmap(QtGui.QPixmap("image/handclick.png"))
        self.label_59.setScaledContents(True)
        self.label_59.setObjectName("label_59")
        self.label_60 = QtWidgets.QLabel(self.tab_6)
        self.label_60.setGeometry(QtCore.QRect(230, 270, 61, 31))
        self.label_60.setText("")
        self.label_60.setPixmap(QtGui.QPixmap("image/arrowRight.png"))
        self.label_60.setScaledContents(True)
        self.label_60.setObjectName("label_60")
        self.tabUserGuide.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.gridLayoutWidget_8 = QtWidgets.QWidget(self.tab_7)
        self.gridLayoutWidget_8.setGeometry(QtCore.QRect(30, 10, 691, 81))
        self.gridLayoutWidget_8.setObjectName("gridLayoutWidget_8")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.gridLayoutWidget_8)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.textBrowser_7 = QtWidgets.QTextBrowser(self.gridLayoutWidget_8)
        self.textBrowser_7.setObjectName("textBrowser_7")
        self.gridLayout_8.addWidget(self.textBrowser_7, 0, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.tab_7)
        self.label_15.setGeometry(QtCore.QRect(30, 100, 441, 411))
        self.label_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("image/Capture_6.0_SearchtoDelete.JPG"))
        self.label_15.setScaledContents(True)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.tab_7)
        self.label_16.setGeometry(QtCore.QRect(540, 160, 171, 61))
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("image/Capture_6.1_QMessage_SureTooDelete.JPG"))
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.tab_7)
        self.label_17.setGeometry(QtCore.QRect(540, 420, 171, 61))
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap("image/Capture_6.2_QMessage_RecordDeleted.JPG"))
        self.label_17.setScaledContents(True)
        self.label_17.setObjectName("label_17")
        self.label_36 = QtWidgets.QLabel(self.tab_7)
        self.label_36.setGeometry(QtCore.QRect(180, 180, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.tab_7)
        self.label_37.setGeometry(QtCore.QRect(440, 180, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.tab_7)
        self.label_38.setGeometry(QtCore.QRect(520, 280, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.tab_7)
        self.label_39.setGeometry(QtCore.QRect(270, 230, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.tab_7)
        self.label_40.setGeometry(QtCore.QRect(400, 190, 31, 41))
        self.label_40.setText("")
        self.label_40.setTextFormat(QtCore.Qt.PlainText)
        self.label_40.setPixmap(QtGui.QPixmap("image/handclick.png"))
        self.label_40.setScaledContents(True)
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.tab_7)
        self.label_41.setGeometry(QtCore.QRect(470, 240, 47, 121))
        font = QtGui.QFont()
        font.setPointSize(72)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.tab_7)
        self.label_42.setGeometry(QtCore.QRect(510, 300, 61, 31))
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.tab_7)
        self.label_43.setGeometry(QtCore.QRect(300, 220, 31, 41))
        self.label_43.setText("")
        self.label_43.setTextFormat(QtCore.Qt.PlainText)
        self.label_43.setPixmap(QtGui.QPixmap("image/handclick.png"))
        self.label_43.setScaledContents(True)
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.tab_7)
        self.label_44.setGeometry(QtCore.QRect(550, 130, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.tab_7)
        self.label_45.setGeometry(QtCore.QRect(550, 390, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.tab_7)
        self.label_46.setGeometry(QtCore.QRect(620, 210, 31, 41))
        self.label_46.setText("")
        self.label_46.setTextFormat(QtCore.Qt.PlainText)
        self.label_46.setPixmap(QtGui.QPixmap("image/handclick.png"))
        self.label_46.setScaledContents(True)
        self.label_46.setObjectName("label_46")
        self.label_47 = QtWidgets.QLabel(self.tab_7)
        self.label_47.setGeometry(QtCore.QRect(660, 470, 31, 41))
        self.label_47.setText("")
        self.label_47.setTextFormat(QtCore.Qt.PlainText)
        self.label_47.setPixmap(QtGui.QPixmap("image/handclick.png"))
        self.label_47.setScaledContents(True)
        self.label_47.setObjectName("label_47")
        self.label_48 = QtWidgets.QLabel(self.tab_7)
        self.label_48.setGeometry(QtCore.QRect(480, 210, 61, 31))
        self.label_48.setText("")
        self.label_48.setPixmap(QtGui.QPixmap("image/arrowRight.png"))
        self.label_48.setScaledContents(True)
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(self.tab_7)
        self.label_49.setGeometry(QtCore.QRect(470, 430, 61, 31))
        self.label_49.setText("")
        self.label_49.setPixmap(QtGui.QPixmap("image/arrowRight.png"))
        self.label_49.setScaledContents(True)
        self.label_49.setObjectName("label_49")
        self.tabUserGuide.addTab(self.tab_7, "")
        self.gridLayout.addWidget(self.tabUserGuide, 0, 0, 1, 1)
        self.btnOkay = QtWidgets.QPushButton(formGuide)
        self.btnOkay.setGeometry(QtCore.QRect(340, 620, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnOkay.setFont(font)
        self.btnOkay.setObjectName("btnOkay")
        self.label_3 = QtWidgets.QLabel(formGuide)
        self.label_3.setGeometry(QtCore.QRect(230, 670, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(7)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.line = QtWidgets.QFrame(formGuide)
        self.line.setGeometry(QtCore.QRect(-10, 660, 771, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.retranslateUi(formGuide)
        self.tabUserGuide.setCurrentIndex(0)
        self.btnOkay.clicked.connect(formGuide.close)
        QtCore.QMetaObject.connectSlotsByName(formGuide)

    def retranslateUi(self, formGuide):
        _translate = QtCore.QCoreApplication.translate
        formGuide.setWindowTitle(_translate("formGuide", "User Guide"))
        self.label_2.setText(_translate("formGuide", "USER GUIDE"))
        self.textBrowser.setHtml(_translate("formGuide", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Open Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; font-size:10pt; color:#000000;\">          This window will guide you on how to use this system. Its purpose is to give information and let you enter a record about student applicant/s like you who want to know the courses the university offers and its requirements. Also, it will give you an instruction to follow if you have successfully availed on the partial course admission. </span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; font-size:10pt; color:#1f3864;\">           The university offers different courses:</span><span style=\" font-size:10pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Symbol\'; font-size:10pt; color:#c00000;\">              </span><span style=\" font-family:\'Times New Roman\'; font-size:10pt; color:#c00000;\">👨🎓‍ </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; color:#c00000;\">Baccalaureate Degree </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Courier New\'; font-size:10pt; color:#7f7f7f;\">    o</span><span style=\" font-family:\'Times New Roman\'; font-size:10pt; color:#7f7f7f;\">   </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; color:#7f7f7f;\">Bachelor of Science in Forestry (</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:600; color:#7f7f7f;\">BSF</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; color:#7f7f7f;\">)</span><span style=\" font-size:10pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Courier New\'; font-size:10pt; color:#7f7f7f;\">    o</span><span style=\" font-family:\'Times New Roman\'; font-size:10pt; color:#7f7f7f;\">   </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; color:#7f7f7f;\">Bachelor of Science in Agriculture (</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:600; color:#7f7f7f;\">BSA</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; color:#7f7f7f;\">)</span><span style=\" font-size:10pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Wingdings\'; font-size:10pt; color:#7f7f7f;\">      §</span><span style=\" font-family:\'Times New Roman\'; font-size:10pt; color:#7f7f7f;\">  </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; color:#7f7f7f;\">Majors :</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Symbol\'; font-size:10pt; color:#7f7f7f;\">        ·</span><span style=\" font-family:\'Times New Roman\'; font-size:10pt; color:#7f7f7f;\">  </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; color:#7f7f7f;\">Animal Science</span><span style=\" font-size:10pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Symbol\'; font-size:10pt; color:#7f7f7f;\">        ·</span><span style=\" font-family:\'Times New Roman\'; font-size:10pt; color:#7f7f7f;\">  </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; color:#7f7f7f;\">Horticulture</span><span style=\" font-size:10pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Symbol\'; font-size:10pt; color:#7f7f7f;\">        ·</span><span style=\" font-family:\'Times New Roman\'; font-size:10pt; color:#7f7f7f;\">  </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; color:#7f7f7f;\">Agronomy</span><span style=\" font-size:10pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Symbol\'; font-size:10pt; color:#7f7f7f;\">        ·</span><span style=\" font-family:\'Times New Roman\'; font-size:10pt; color:#7f7f7f;\">  </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; color:#7f7f7f;\">Crop Production</span><span style=\" font-size:10pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Symbol\'; font-size:10pt; color:#7f7f7f;\">        ·</span><span style=\" font-family:\'Times New Roman\'; font-size:10pt; color:#7f7f7f;\">  </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; color:#7f7f7f;\">Agricultural Economics</span><span style=\" font-size:10pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Courier New\'; font-size:10pt; color:#7f7f7f;\">    o</span><span style=\" font-family:\'Times New Roman\'; font-size:10pt; color:#7f7f7f;\">   </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; color:#7f7f7f;\">Bachelor of Science in Industrial Engineering (</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:600; color:#7f7f7f;\">BSIE</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; color:#7f7f7f;\">)</span><span style=\" font-size:10pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Courier New\'; font-size:10pt; color:#7f7f7f;\">    o</span><span style=\" font-family:\'Times New Roman\'; font-size:10pt; color:#7f7f7f;\">   </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; color:#7f7f7f;\">Bachelor of Science in Information Technology (</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:600; color:#7f7f7f;\">BSIT</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; color:#7f7f7f;\">)</span><span style=\" font-size:10pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Courier New\'; font-size:10pt; color:#7f7f7f;\">    o</span><span style=\" font-family:\'Times New Roman\'; font-size:10pt; color:#7f7f7f;\">   </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; color:#7f7f7f;\">Bachelor of Science in Hospitality Management (</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:600; color:#7f7f7f;\">BSHM</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; color:#7f7f7f;\">)</span><span style=\" font-size:10pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Courier New\'; font-size:10pt; color:#7f7f7f;\">    o</span><span style=\" font-family:\'Times New Roman\'; font-size:10pt; color:#7f7f7f;\">   </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; color:#7f7f7f;\">Bachelor of Elementary Education (</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:600; color:#7f7f7f;\">BEED</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; color:#7f7f7f;\">)</span><span style=\" font-size:10pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Courier New\'; font-size:10pt; color:#7f7f7f;\">    o</span><span style=\" font-family:\'Times New Roman\'; font-size:10pt; color:#7f7f7f;\">   </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; color:#7f7f7f;\">Bachelor of Technology and Livelihood Education major in Home Economics (</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:600; color:#7f7f7f;\">BTLEd</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; color:#7f7f7f;\">)</span><span style=\" font-size:10pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Courier New\'; font-size:10pt; color:#7f7f7f;\">    o</span><span style=\" font-family:\'Times New Roman\'; font-size:10pt; color:#7f7f7f;\">   </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; color:#7f7f7f;\">Bachelor of Secondary Education major in Math (</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:600; color:#7f7f7f;\">BSED-Math</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; color:#7f7f7f;\">)</span><span style=\" font-size:10pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Courier New\'; font-size:10pt; color:#7f7f7f;\">    o</span><span style=\" font-family:\'Times New Roman\'; font-size:10pt; color:#7f7f7f;\">   </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; color:#7f7f7f;\">Bachelor of Arts in English Language Studies (</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:600; color:#7f7f7f;\">AB-ELs</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; color:#7f7f7f;\">)</span><span style=\" font-size:10pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Courier New\'; font-size:10pt; color:#7f7f7f;\">    o</span><span style=\" font-family:\'Times New Roman\'; font-size:10pt; color:#7f7f7f;\">   </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; color:#7f7f7f;\">Bachelor of Arts in Literature (</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:600; color:#7f7f7f;\">AB-Lit</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; color:#7f7f7f;\">)</span><span style=\" font-size:10pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Courier New\'; font-size:10pt; color:#7f7f7f;\">    o</span><span style=\" font-family:\'Times New Roman\'; font-size:10pt; color:#7f7f7f;\">   </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; color:#7f7f7f;\">Bachelor in Industrial Technology (</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:600; color:#7f7f7f;\">BIT</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; color:#7f7f7f;\">)</span><span style=\" font-size:10pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Wingdings\'; font-size:10pt; color:#7f7f7f;\">      §</span><span style=\" font-family:\'Times New Roman\'; font-size:10pt; color:#7f7f7f;\">  </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; color:#7f7f7f;\">Majors :</span><span style=\" font-size:10pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Symbol\'; font-size:10pt; color:#7f7f7f;\">        ·</span><span style=\" font-family:\'Times New Roman\'; font-size:10pt; color:#7f7f7f;\">  </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; color:#7f7f7f;\">Garments Technology</span><span style=\" font-size:10pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Symbol\'; font-size:10pt; color:#7f7f7f;\">        ·</span><span style=\" font-family:\'Times New Roman\'; font-size:10pt; color:#7f7f7f;\">  </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; color:#7f7f7f;\">Automotive Technology</span><span style=\" font-size:10pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Symbol\'; font-size:10pt; color:#7f7f7f;\">        ·</span><span style=\" font-family:\'Times New Roman\'; font-size:10pt; color:#7f7f7f;\">  </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; color:#7f7f7f;\">Computer Technology</span><span style=\" font-size:10pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Symbol\'; font-size:10pt; color:#7f7f7f;\">        ·</span><span style=\" font-family:\'Times New Roman\'; font-size:10pt; color:#7f7f7f;\">  </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; color:#7f7f7f;\">Drafting Technology</span><span style=\" font-size:10pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Symbol\'; font-size:10pt; color:#7f7f7f;\">        ·</span><span style=\" font-family:\'Times New Roman\'; font-size:10pt; color:#7f7f7f;\">  </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; color:#7f7f7f;\">Electronics Technology</span><span style=\" font-size:10pt;\"> </span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%; font-size:10pt;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Times New Roman\'; font-size:10pt; color:#c00000;\">              👨‍⚖️ </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; color:#c00000;\">Graduate School courses</span><span style=\" font-size:10pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Courier New\'; font-size:10pt; color:#7f7f7f;\">    o</span><span style=\" font-family:\'Times New Roman\'; font-size:10pt; color:#7f7f7f;\">   </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; color:#7f7f7f;\">Doctor in Development Education (</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:600; color:#7f7f7f;\">Dev.Ed.D.</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; color:#7f7f7f;\">)</span><span style=\" font-size:10pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Courier New\'; font-size:10pt; color:#7f7f7f;\">    o</span><span style=\" font-family:\'Times New Roman\'; font-size:10pt; color:#7f7f7f;\">   </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; color:#7f7f7f;\">Doctor in Philosophy major in Technology Management (</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:600; color:#7f7f7f;\">Ph.D. TM</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; color:#7f7f7f;\">)</span><span style=\" font-size:10pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Courier New\'; font-size:10pt; color:#7f7f7f;\">    o</span><span style=\" font-family:\'Times New Roman\'; font-size:10pt; color:#7f7f7f;\">   </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; color:#7f7f7f;\">Master of Arts in Education major in Administration and Supervision (</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:600; color:#7f7f7f;\">M.A.Ed. -AS</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; color:#7f7f7f;\">)</span><span style=\" font-size:10pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Courier New\'; font-size:10pt; color:#7f7f7f;\">    o</span><span style=\" font-family:\'Times New Roman\'; font-size:10pt; color:#7f7f7f;\">   </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; color:#7f7f7f;\">Master of Arts in Education major in Teaching Mathematics (</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:600; color:#7f7f7f;\">MAEd-TM</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; color:#7f7f7f;\">)</span><span style=\" font-size:10pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Courier New\'; font-size:10pt; color:#7f7f7f;\">    o</span><span style=\" font-family:\'Times New Roman\'; font-size:10pt; color:#7f7f7f;\">   </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; color:#7f7f7f;\">Master of Arts in Education major in English Language &amp; Literature Teaching (</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:600; color:#7f7f7f;\">MAed-ELLT</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; color:#7f7f7f;\">)</span><span style=\" font-size:10pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Courier New\'; font-size:10pt; color:#7f7f7f;\">    o</span><span style=\" font-family:\'Times New Roman\'; font-size:10pt; color:#7f7f7f;\">   </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; color:#7f7f7f;\">Master of Arts in Vocational Education (</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:600; color:#7f7f7f;\">MAVEd</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; color:#7f7f7f;\">)</span><span style=\" font-size:10pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Courier New\'; font-size:10pt; color:#7f7f7f;\">    o</span><span style=\" font-family:\'Times New Roman\'; font-size:10pt; color:#7f7f7f;\">   </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; color:#7f7f7f;\">Master in Public Administration (</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:600; color:#7f7f7f;\">MPA</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; color:#7f7f7f;\">)</span><span style=\" font-size:10pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:106%;\"><span style=\" font-family:\'Courier New\'; font-size:10pt; color:#7f7f7f;\">    o</span><span style=\" font-family:\'Times New Roman\'; font-size:10pt; color:#7f7f7f;\">   </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; color:#7f7f7f;\">Diploma / Certificate in Professional Education (</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:600; color:#7f7f7f;\">DPE/CPE</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; color:#7f7f7f;\">)</span><span style=\" font-size:10pt;\"> </span></p></body></html>"))
        self.tabUserGuide.setTabText(self.tabUserGuide.indexOf(self.tab), _translate("formGuide", "Introduction"))
        self.textBrowser_2.setHtml(_translate("formGuide", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Open Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%;\"><span style=\" font-size:11pt; font-weight:600;\">1.</span><span style=\" font-family:\'Times New Roman\'; font-size:11pt; font-weight:600;\">  </span><span style=\" font-family:\'Times New Roman\'; font-size:10pt;\">     </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt;\">Select your admission type through clicking the buttons of your choice from the main window.</span><span style=\" font-size:10pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%;\"><span style=\" font-family:\'Segoe UI Emoji\'; font-size:10pt;\">         🤗 </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt;\">  Are you a/an:</span><span style=\" font-size:10pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%;\"><span style=\" font-family:\'Segoe UI\'; font-size:10pt;\">    ~ Incoming Freshman</span><span style=\" font-size:10pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%;\"><span style=\" font-family:\'Segoe UI\'; font-size:10pt;\">    ~ Transferee</span><span style=\" font-size:10pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%;\"><span style=\" font-family:\'Segoe UI\'; font-size:10pt;\">    ~ Old Student</span><span style=\" font-size:10pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%;\"><span style=\" font-family:\'Segoe UI\'; font-size:10pt;\">    ~ Second Degree Applicant</span><span style=\" font-size:10pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%;\"><span style=\" font-family:\'Segoe UI\'; font-size:10pt;\">    ~ Graduate School Applicant</span> </p></body></html>"))
        self.tabUserGuide.setTabText(self.tabUserGuide.indexOf(self.tab_3), _translate("formGuide", "1: Selecting Admission Type in Main Window"))
        self.textBrowser_3.setHtml(_translate("formGuide", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Open Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600;\">2.</span><span style=\" font-family:\'Times New Roman\'; font-size:11pt; font-weight:600;\">   </span><span style=\" font-family:\'Times New Roman\'; font-size:10pt;\">  </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt;\">After clicking, a new window will appear. This is where you can input your information and view the general requirements to enroll a course program.</span><span style=\" font-size:10pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; font-size:10pt;\">                    </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; text-decoration: underline;\">Example</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt;\">: </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-style:italic;\">Old Student</span><span style=\" font-size:10pt;\"> </span></p></body></html>"))
        self.tabUserGuide.setTabText(self.tabUserGuide.indexOf(self.tab_2), _translate("formGuide", "2: Showing Choosen Admission Window"))
        self.textBrowser_4.setHtml(_translate("formGuide", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Open Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600;\">3.</span><span style=\" font-family:\'Times New Roman\'; font-size:11pt; font-weight:600;\">   </span><span style=\" font-family:\'Times New Roman\'; font-size:7pt;\">    </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt;\">After entering your information, you can click </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:600; font-style:italic;\">Clear</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt;\"> if you entered wrong information or simply going to the field where you think you must edit.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; font-size:10pt;\">    </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:600;\">3.1.</span><span style=\" font-family:\'Times New Roman\'; font-size:7pt;\">   </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-style:italic;\">Then, if all fields are filled in, click the </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:600; font-style:italic;\">Submit </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-style:italic;\">button to </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:600; font-style:italic;\">view</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-style:italic;\"> your information. </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:600;\">    3.2.</span><span style=\" font-family:\'Times New Roman\'; font-size:7pt;\">   </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-style:italic;\">A message dialog will appear, states that  </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:600; font-style:italic;\">\'You can view your record now.\' </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-style:italic;\">Click</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:600; font-style:italic;\"> OK</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-style:italic;\">.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:600;\">    3.3.</span><span style=\" font-family:\'Times New Roman\'; font-size:7pt;\">   </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-style:italic;\">Finally, click the </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:600; font-style:italic;\">Add</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-style:italic;\"> button to save your information / record. </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; font-size:10pt;\">    </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:600;\">3.4.</span><span style=\" font-family:\'Times New Roman\'; font-size:7pt;\">   </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-style:italic;\">A message dialog will show if you’re qualified or not. Click </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:600; font-style:italic;\">OK</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-style:italic;\">.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-style:italic;\">         </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt;\">If you want to exit the window, click </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:600;\">X</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt;\"> or the </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:600; font-style:italic;\">Cancel</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt;\"> button.</span></p></body></html>"))
        self.label_18.setText(_translate("formGuide", "3.1     "))
        self.label_19.setText(_translate("formGuide", "3.2    "))
        self.label_20.setText(_translate("formGuide", "3.3  "))
        self.label_53.setText(_translate("formGuide", "3.4  "))
        self.tabUserGuide.setTabText(self.tabUserGuide.indexOf(self.tab_4), _translate("formGuide", "3: Enter Info-View-Add Record"))
        self.textBrowser_5.setHtml(_translate("formGuide", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Open Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600;\">4.</span><span style=\" font-family:\'Times New Roman\'; font-size:11pt; font-weight:600;\"> </span><span style=\" font-family:\'Times New Roman\'; font-size:7pt;\">      </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt;\">If you had complete requirements, the message dialog shows that </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:600; font-style:italic;\">‘You can proceed to the Registrar Office &amp; to your desired Department to fully enroll. (</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-style:italic;\">Click</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:600; font-style:italic;\"> OK)’</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt;\"> However, if you’re incomplete, the dialog shows to </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:600; font-style:italic;\">‘Complete the requirements first before going to the Registrar Office &amp; to your desired Department’ (</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-style:italic;\">Click</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:600; font-style:italic;\"> OK)</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-style:italic;\">.</span><span style=\" font-size:10pt;\"> </span></p></body></html>"))
        self.label_11.setText(_translate("formGuide", "Complete Requirements"))
        self.label_12.setText(_translate("formGuide", "Incomplete Requirements"))
        self.tabUserGuide.setTabText(self.tabUserGuide.indexOf(self.tab_5), _translate("formGuide", "4: Record Added Message "))
        self.textBrowser_6.setHtml(_translate("formGuide", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Open Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600;\">5.</span><span style=\" font-family:\'Times New Roman\'; font-size:11pt; font-weight:600;\">   </span><span style=\" font-family:\'Times New Roman\'; font-size:7pt;\">    </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt;\">If you had incomplete requirements, you can edit your information by entering the information to search depending on what admission window you’re in. Then, click the </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:600; font-style:italic;\">Search</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt;\"> button to </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:600; font-style:italic;\">update</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt;\"> your record. </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:600;\">    5.1.</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-style:italic;\"> In the example below, </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:600; font-style:italic;\">enter</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-style:italic;\"> your ‘</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:600; font-style:italic;\">ID Number to search’ </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-style:italic;\">tab.</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:600;\">    5.2.</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt;\"> </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-style:italic;\">Click the</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:600; font-style:italic;\">🔍 Search </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-style:italic;\">icon.</span><span style=\" font-style:italic;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:600;\">    5.3.</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt;\"> </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-style:italic;\">After your information is displayed, you can </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:600; font-style:italic;\">edit the fields</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-style:italic;\"> you want to update.</span> </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:600;\">    5.4.</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt;\"> </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-style:italic;\">Click the </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:600; font-style:italic;\">Submit</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-style:italic;\"> button to view your edited record.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-style:italic;\">    </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:600;\">5.5.</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt;\"> </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-style:italic;\">A message will appear, states that \'</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:600; font-style:italic;\">You can view your record now.</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-style:italic;\">\'. Click </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:600; font-style:italic;\">OK</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-style:italic;\">.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:600;\">    5.6.</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt;\"> </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-style:italic;\">Then, click the </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:600; font-style:italic;\">Update</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-style:italic;\"> button to update your record.</span><span style=\" font-style:italic;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-style:italic;\">    </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:600;\">5.7.</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt;\"> </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-style:italic;\">Finally, a message will appear that shows that it had successfully updated the record. Click </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:600; font-style:italic;\">OK.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; font-size:10pt;\">    </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; text-decoration: underline;\">Example:</span></p></body></html>"))
        self.label_26.setText(_translate("formGuide", "5.1    "))
        self.label_27.setText(_translate("formGuide", "5.2"))
        self.label_28.setText(_translate("formGuide", "5.3   "))
        self.label_29.setText(_translate("formGuide", "5.4 "))
        self.label_30.setText(_translate("formGuide", "{"))
        self.label_32.setText(_translate("formGuide", "5.5  "))
        self.label_35.setText(_translate("formGuide", "Displaying, Edit fields"))
        self.label_54.setText(_translate("formGuide", "5.6  "))
        self.label_55.setText(_translate("formGuide", "5.7"))
        self.tabUserGuide.setTabText(self.tabUserGuide.indexOf(self.tab_6), _translate("formGuide", "5: Search-Update Record"))
        self.textBrowser_7.setHtml(_translate("formGuide", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Open Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600;\">6.</span><span style=\" font-family:\'Times New Roman\'; font-size:7pt;\">       </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt;\">To </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:600; font-style:italic;\">delete</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt;\"> your record, enter the information asked to search also, then click 🔍</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:600; font-style:italic;\">Search</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt;\"> icon again. Lastly, after your information is displayed, click the </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:600; font-style:italic;\">Delete</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt;\"> button to delete your record. A message dialog appears stating, \'</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:600; font-style:italic;\">Are you sure to delete your record?</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt;\">\'</span> , <span style=\" font-family:\'Segoe UI\'; font-size:10pt;\">you can click </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:600;\">YES </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt;\">or </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:600;\">NO. </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt;\">If you click</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:600;\"> YES , </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt;\">a message dialog will show that</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:600;\"> \'</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:600; font-style:italic;\">Your record had successfully deleted.</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:600;\">\'</span><span style=\" font-family:\'Segoe UI\'; font-size:10pt;\">.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; font-size:10pt;\">    </span><span style=\" font-family:\'Segoe UI\'; font-size:10pt; text-decoration: underline;\">Example:</span> </p></body></html>"))
        self.label_36.setText(_translate("formGuide", "6.1    "))
        self.label_37.setText(_translate("formGuide", "6.2"))
        self.label_38.setText(_translate("formGuide", "6.3"))
        self.label_39.setText(_translate("formGuide", "6.4"))
        self.label_41.setText(_translate("formGuide", "}"))
        self.label_42.setText(_translate("formGuide", "Displaying"))
        self.label_44.setText(_translate("formGuide", "6.5"))
        self.label_45.setText(_translate("formGuide", "6.6"))
        self.tabUserGuide.setTabText(self.tabUserGuide.indexOf(self.tab_7), _translate("formGuide", "6: Search-Delete Record"))
        self.btnOkay.setText(_translate("formGuide", "CLOSE"))
        self.label_3.setText(_translate("formGuide", "© 2020 Partial Course Admission System (PCAS). All rights reserved."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    formGuide = QtWidgets.QWidget()
    ui = Ui_formGuide()
    ui.setupUi(formGuide)
    formGuide.show()
    sys.exit(app.exec_())
